### ISSUE TITLE
Can I interact with the desktop?

### ISSUE THREAD

**Issue by curzel-it** [rocksdanister/lively#10]
Say I want to set my wallpaper as a web page that requires credentials (eg. Google Keep or Trello).
Is there any way I can interact with the desktop to login?

**Comment by rocksdanister** [comment]
Cef is set to use memory as cache... so when you restart browser the login & other cookie data disappears.

I'm working on an input system through lively for interaction, you can see a working demo on the subreddit: https://www.reddit.com/r/LivelyWallpaper/comments/ew5e3e/preview_web_wallpaper_input_test_3_rain/

**Comment by curzel-it** [comment]
> Not sure If i should provide a toggle for it, safety concerns and all that.
Maybe on a per-wallpaper basis, what do you think?
> https://www.reddit.com/r/LivelyWallpaper/comments/ew5e3e/preview_web_wallpaper_input_test_3_rain/
Amazing!

**Comment by rocksdanister** [comment]
I think il add an optional flag in the LivelyInfo.json file after next update, no gui.

**Comment by rocksdanister** [comment]
Mouse interaction is coming next update: https://youtu.be/mhhmV-DSjGY

**Comment by rocksdanister** [comment]
I'm working on keyboard input: https://github.com/rocksdanister/lively/issues/35
& there will be a setting in Lively to enable disk cache for cef.

Will take time as I'm currently refactoring the code.

**Comment by rocksdanister** [comment]
Recently added a preview mode with full input support:
https://github.com/rocksdanister/lively/releases/tag/v1.0.7.0
Since its just a separate window in-focus run temporarily, safety is not a problem.
Now only left to enable the disk cache mode in cef so that login persists.

**Comment by rocksdanister** [comment]
Its possible now:
1. Enable Disk cache so that cookie and login settings gets restored next time browser is started.
2. Open the wallpaper that require input in Preview mode.
3. Enter the credentials and select "Keep me Logged in" or similar option, login to the service.
4. Close preview and now just set the wallpaper normally.

**Note:**
- Cachepath is separate depending on the selected screen, so for example if first screen is selected in lively control panel then cache folder will be for that screen only.
- Disk cache will be only enabled for online type wallpapers.
- Cache location is: `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\Cef`

This is safe as the input is only forwarded when the preview window is in focus, you can keep track of the keyboard interaction for wallpaper in separate issue: https://github.com/rocksdanister/lively/issues/35

![disk cache](https://user-images.githubusercontent.com/17554161/93769204-1e016f00-fc38-11ea-8bd5-5a88c179e47b.jpg)

![Screenshot 2020-09-21 182701](https://user-images.githubusercontent.com/17554161/93769211-2194f600-fc38-11ea-8eff-1a0a675f0f83.jpg)

![preview](https://user-images.githubusercontent.com/17554161/93769221-25287d00-fc38-11ea-9e0a-e9d2a5e35b1c.jpg)

**Comment by rocksdanister** [comment]
Lively v2.2 state is per-layout (span, duplicate..) and monitor. So the login has to be done when running as wallpaper (not edit or preview.)
