### ISSUE TITLE
Can't launch the app or uninstall

### ISSUE THREAD

**Issue by Pleasehelpmeok** [rocksdanister/lively#103]
[20200819_202158.txt](https://github.com/rocksdanister/lively/files/5100529/20200819_202158.txt)
I get error logs help

**Comment by rocksdanister** [comment]
Describe the error, follow the template for bug.

**Comment by Pleasehelpmeok** [comment]
I dont know anything about it
can you explain it?

**Comment by Pleasehelpmeok** [comment]
Single Display Mode:- Screen[Bounds={X=0,Y=0,Width=1920,Height=1080} WorkingArea={X=0,Y=0,Width=1920,Height=1040} Primary=True DeviceName=\\.\DISPLAY1 says that

**Comment by rocksdanister** [comment]
Fill this:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Comment by Pleasehelpmeok** [comment]
Describe the bug
Basically I tried to change my wallpaper and I went to task manager and ended task and it stopped working
Expected behavior
I expected it to stop because usually when I end task it stops working but then it just stopped working, and also it say its running and to open it I need to end task
Screenshots/Video
https://youtu.be/Lfe1rRR76d0
Additional context
It worked when I downloaded it for the first time then when I ended the task it stopped working

**Comment by rocksdanister** [comment]
Lively is running in the system-tray, to Exit access the system-tray menu
See this: https://github.com/rocksdanister/lively/issues/101

**Comment by Pleasehelpmeok** [comment]
ok

**Comment by Pleasehelpmeok** [comment]
tysm
