### ISSUE TITLE
The Wallpaper Disappears

### ISSUE THREAD

**Issue by donRumata03** [rocksdanister/lively#106]
The Wallpaper disappears when pressing Alt + Tab.
Does it behave the same way on other devices or do I have some problems with installation / system / e.t.c.?
I`m using Windows 10 LTSC (does it matter?..)

To reproduce the bug, simply press Win + D, then while holding Alt, press and release the Tab key. The Screen becomes Black for me.

**Comment by rocksdanister** [comment]
This has been resolved in v1.0, its because of the way I implemented the process monitor algorithm for pausing wallpaper playback.

With the new algorithm I'm checking for Classnames of Windows UI elements:https://github.com/rocksdanister/lively/blob/16764c7585d13775ae2ecdbe98d89b3c2e319347/src/livelywpf/livelywpf/Core/Monitor/Playback.cs#L15

**Comment by donRumata03** [comment]
Augh, thank you very much!
Sorry for bothering you

Pretty reasonable solution...
