### ISSUE TITLE
Have to reset wallpaper on boot up.

### ISSUE THREAD

**Issue by nbsymmons** [rocksdanister/lively#108]
I installed Lively on a fresh Windows 10 PC. I set my wallpaper to simply span across the two displays. When restarting or booting up, I have to then enter Lively and reset this manually.

 - OS: Windows 10 (2004/19041.450)
- Which wallpaper was running at the time if any: Matrix (Sample)

No error log directory but I've attached the logfile.txt accordingly.
[logfile.txt](https://github.com/rocksdanister/lively/files/5137496/logfile.txt)

**Comment by rocksdanister** [comment]
Its because I'm using the screename string to compare and restore wallpaper; this string is not unique to a display and can change during reboot, driver install etc.

In v1.0 I'm comparing the display dimension and position instead and in my limited testing its been resolved.
https://github.com/rocksdanister/lively/blob/7f67d447b47a5658c4c674e922df81b61507d5da/src/livelywpf/livelywpf/Helpers/ScreenHelper.cs#L152

Make a new issue if you still have problem after v1.0 release.
