### ISSUE TITLE
Several wallpapers not working due to CORS issue in loading file URL resources while using MS Edge Engine

### ISSUE THREAD

**Issue by LaplaceDaemon101** [rocksdanister/lively#1160]
**Describe the bug**
Several of the default wallpapers such as "Rain v2", "Ripples" are unable to load and will either just show a blank screen or partially function without any images. This only happens while using MS Edge Webview Engine. Further digging deeper into this got me that the requests for resources such as images are blocked by CORS policy.

**To Reproduce**
1. Set the Web Browser engine to "MS Edge".
2. Try opening "Rain v2" in preview.
3. Open web inspector using keyboard shortcut and go to console. You will see the requests from file URL to another file URL being blocked.

**Expected behavior**
Simply the wallpapers should work in any engine as they are intended to.

**Screenshots/Video**
Here are screenshots detailing the evident case while loading "Rain v2":
![1 Wallpaper issue](https://user-images.githubusercontent.com/91762460/161386783-48dbd218-fc65-48e1-95c6-740894372915.jpg)

![2 CORS](https://user-images.githubusercontent.com/91762460/161386802-b5090324-481c-4d44-834b-3fa7b27cabc5.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 2004 
- Wallpaper "Rain v2" and "Ripples" preinstalled within the app.

**Additional context**
Possible Solution:
Maybe this issue could be bypassed by setting edge://flags but I don't want to make a highly OS coupled browser vulnerable. While searching for other solutions I found this [StackOverflow Answer](https://stackoverflow.com/questions/63404822/how-to-disable-cors-in-wpf-webview2). We just need to allow file resource access grant so we can use the flag `"--allow-file-access-from-files"` as mentioned in comment by mbassett on the first answer and use the rest of the suggestion in 1st answer. I guess by writing `var op = new CoreWebView2EnvironmentOptions("--allow-file-access-from-files");` and setting it as a parameter to the line 86 of the file [lively/src/Lively/Lively.PlayerWebView2/MainWindow.xaml.cs](https://github.com/rocksdanister/lively/blob/core-separation/src/Lively/Lively.PlayerWebView2/MainWindow.xaml.cs) might fix this.

**Log file (Important)**
Log file attached here:
[lively_log_20220402_150750.zip](https://github.com/rocksdanister/lively/files/8402676/lively_log_20220402_150750.zip)

**Comment by rocksdanister** [comment]
This is known issue, Edge webview player is still under development and not primary browser:
https://github.com/rocksdanister/lively/wiki/Web-Guide-I-:-Cef

`--allow-file-access-from-files` is not used due to security reasons.

In CefSharp custom schemehandler is used for fetching resources; schemehandler is not supported by WebView2 yet:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1825

`SetVirtualHostNameToFolderMapping` is an option but that involes also modifying the html files:
https://github.com/rocksdanister/lively/blob/3d8d3982154969be333b80903dffbcf16a4cd4a0/src/Lively/Lively.PlayerWebView2/MainWindow.xaml.cs#L117

Another option is to start a localhost server but that seemed like too much - starting a new server for each wallpapers.

For now waiting for WebView2 to support custom schemehandler.

There are also other concerns with using WebView2 - the method I use to pause browser rendering is not official and this is not thoroughly tested in WebView2 yet (especially since webview shares resources(?) with other apps.)

**Comment by roxxel** [comment]
Possible solution is to implement CORS proxy server in lively and run it locally then

**Comment by roxxel** [comment]
@rocksdanister hey, can u assign me for this issue? I'll fix it

**Comment by roxxel** [comment]
> Another option is to start a localhost server but that seemed like too much - starting a new server for each wallpapers.

There's lightweight http server like Watson

**Comment by rocksdanister** [comment]
I still think its better to just wait for:
`For now waiting for WebView2 to support custom schemehandler.`

If you are implementing it, will it be in the core program or the browser program?
https://github.com/rocksdanister/lively/tree/core-separation/src/Lively/Lively
https://github.com/rocksdanister/lively/tree/core-separation/src/Lively/Lively.PlayerWebView2
