### ISSUE TITLE
Video wallpaper crash

### ISSUE THREAD

**Issue by stevo1989** [rocksdanister/lively#1166]
lively closes itself after a few days. then today the size of the animated video was smaller than my screen, so I saw the normal windows background below
[lively_log_20220405_191606.zip](https://github.com/rocksdanister/lively/files/8422189/lively_log_20220405_191606.zip)

**Comment by rocksdanister** [comment]
`GPU: NVIDIA GeForce 210`
Its most likely the gpu being too old (2009) and driver quality(?)

You can try turning off GPU decode and see if that helps:
![image](https://user-images.githubusercontent.com/17554161/161897748-64ab81b2-b229-45eb-a079-b3d078dfc808.png)

Closing this because the hardware does not meet minimum requirement.
