### ISSUE TITLE
Hardware acceleration

### ISSUE THREAD

**Issue by Thomas-SuS** [rocksdanister/lively#129]
Please can you add a hardware acceleration option
My processor is used at ~30% when I set a 4k video, it causes performance problems just for display the windows in Windows 10
If it can run on my graphical card It would be much much better 
I have try to manually set it but i don't succed so I think it's not possible for now
Thank you

**Comment by rocksdanister** [comment]
Its enabled.
https://github.com/rocksdanister/lively/blob/a647198d6358e027c23e6d375afd9609d2305e36/src/livelywpf/libMPVPlayer/MainWindow.xaml.cs#L63

Its likely because you are running unsupported video codec for your video decoding hardware.
Recommended video format for video wallpaper considering load is 1080p/720p x264.
If working correctly taskmanager will show it as **Video Decode** in GPU Engine section.
Forther read: https://github.com/rocksdanister/lively/wiki/Performance
