### ISSUE TITLE
Lively Wallpaper crashing when i click add new wallpaper and settings

### ISSUE THREAD

**Issue by eriksaalihu** [rocksdanister/lively#1360]
Idk whats happening i just installed windows 11 and this is happening and not letting me add a new wallpaper besides the existing ones

**Comment by rocksdanister** [comment]
**Fill the issue template:**

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Navigate to Appdata folder:
`C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
or
`%LocalAppData%\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper`

**Comment by eriksaalihu** [comment]
https://user-images.githubusercontent.com/98664536/185966760-e1421f4f-af1c-4d29-8b95-179593c1433a.mp4

Windows 11

**Comment by rocksdanister** [comment]
Looks like its running elevated (Run as admin), re-enable UAC driver https://github.com/rocksdanister/lively/issues/1060#issuecomment-1044970174

Also if you have tools like MSI Afterburner try turning it off and see.

**Comment by eriksaalihu** [comment]
> Looks like its running elevated (Run as admin), re-enable UAC driver [#1060 (comment)](https://github.com/rocksdanister/lively/issues/1060#issuecomment-1044970174)
> 
> Also if you have tools like MSI Afterburner try turning it off and see.

**Comment by eriksaalihu** [comment]
i was on winver  22621.132 i think and the download was only 299mb or something (couldnt find any solution for this problem), but when i  reinstalled with winver 22621.232 which is newer the download was 330 or something mb and now its working. No idea why that happened

**Comment by rocksdanister** [comment]
This is what the doc says:
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#elevation

>Elevated support requires the following OS servicing update:
Win11 - [May 10, 2022—KB5013943 (OS Build 22000.675)](https://support.microsoft.com/topic/may-10-2022-kb5013943-os-build-22000-675-14aa767a-aa87-414e-8491-b6e845541755)
Win10 - [May 10, 2022—KB5013942 (OS Builds 19042.1706, 19043.1706, and 19044.1706)](https://support.microsoft.com/topic/may-10-2022-kb5013942-os-builds-19042-1706-19043-1706-and-19044-1706-60b51119-85be-4a34-9e21-8954f6749504)
