### ISSUE TITLE
Website background missing

### ISSUE THREAD

**Issue by SamuelStevenson** [rocksdanister/lively#1403]
**Describe the bug**
All the elements on the website https://app.lofi.co/ work except for the background. A black screen is displayed instead.

**To Reproduce**
1. Add https://app.lofi.co/ as a new Lively Wallpaper
2. Click on '...' and then 'Preview' to see the missing website background, OR
3. Click on '...' and then 'Set As Background' to see the missing website background

**Expected behavior**
Website is displayed with background, as in a regular browser session.

**Screenshots/Video**
It looks like this: ![image](https://user-images.githubusercontent.com/42255596/192342529-75a88b4b-78d6-4d45-9bd9-25a4bf4871dc.png)

But it should look like this: 
![image](https://user-images.githubusercontent.com/42255596/192342717-23d9d7f4-e853-4271-819f-c3b3a493574d.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home - 22H2

**Log file (Important)**
[lively_log_20220926_102658.zip](https://github.com/rocksdanister/lively/files/9648402/lively_log_20220926_102658.zip)

**Comment by rocksdanister** [comment]
[CefSharp(the current default browser) don't support x264 video codec due to licensing.](https://github.com/rocksdanister/lively/wiki/Web-Guide-VI-:-Webpage-Video-Support)

[WebView2 supports it, its still under development but works fine for urls.](https://github.com/rocksdanister/lively/wiki/Web-Player)
