### ISSUE TITLE
Static image consumes CPU

### ISSUE THREAD

**Issue by nulkode** [rocksdanister/lively#1411]
**Describe the bug**
When you set a static image as background, the application consumes CPU, while if you pause the background through the hidden menu, it does not require CPU achieving the same effect. 

**To Reproduce**
1. Set a static image as background
2. See that the application is consuming CPU for no reason

**Expected behavior**
The application shouldn't require CPU to display an static image

**Desktop (please complete the following information):**
 - OS: Windows 11 (21H2)
- I'm using two screens

**Additional context**
I am using static images with Lively Wallpaper because Windows does not support displaying two different images per screen. The application should understand that it is a static image and should automatically pause the background and not consume CPU by rendering a static image.

**Comment by rocksdanister** [comment]
Lively is designed primarily for live wallpapers so as a simple solution video player is used to render static image wallpapers.. not proud of it but it worked and I never imagined many used this feature. There is a plan to use native windows api to set static picture wallpaper but it will take some time since it should behave similar to other lively live wallpaper features such as restoring previous wallpaper when closing, screensaver etc..

>I am using static images with Lively Wallpaper because Windows does not support displaying two different images per screen.

Windows supports this, right click the image and you will get the option:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/17554161/194624968-250fe260-99da-4e1e-9aa4-3a70838eef4a.png">
 (close any virtual desktop(s) first if any open otherwise you will get desktop instead of display.)
