### ISSUE TITLE
Checkbox "Play audio only when desktop is focused" is not working.

### ISSUE THREAD

**Issue by alient12** [rocksdanister/lively#1428]
**Describe the bug**
checkbox "Play audio only when desktop is focused" is not working. when I uncheck it, the sound gets mute after I open a window.

**To Reproduce**
1. set a video with sound as wallpaper
2. uncheck "Play audio only when desktop is focused"
3. go to desktop, you hear the sound
4. open an app, you don't hear the sound anymore

**Expected behavior**
I want to hear the sound when I'm using another apps

**Desktop (please complete the following information):**
 - OS: Windows 11 Home 21H2 22000.1098
- Which wallpaper was running at the time if any: v2.0.4.0

[lively_log_20221016_132951.zip](https://github.com/rocksdanister/lively/files/9794128/lively_log_20221016_132951.zip)

**Comment by rocksdanister** [comment]
Is the app fullscreen or do you have pause wallpaper when app is open? if the wallpaper is paused the audio will also pause since both video and audio is handled by same player.

There is an option to [disable video track](https://mpv.io/manual/stable/#options-vid) - have to check if possible to re-enable it once disabled and maybe that can be used to just keep audio track playing.

**Comment by alient12** [comment]
Thank you for your response. I see the problem was with fullscreen.
