### ISSUE TITLE
mpv default configuration is not getting right results on some hdr setups.

### ISSUE THREAD

**Issue by Semidio** [rocksdanister/lively#1482]
**Is your feature request related to a problem? Please describe.**

The SDR video is not presented in right color on HDR screen with the default mpv configuration when Windows HDR is set to on. And the store version lively is unable to change the mpv configuration, sandbox restriction.

**Describe the solution you'd like**

Include the configuration that will let mpv output the more accurate color for HDR setup.
etc
`vo=gpu-next
target-colorspace-hint=yes`

**Describe alternatives you've considered**

Have a way to change the configuration used by internal mpv with store version.

**Additional context**
Add any other context or screenshots/mockups about the feature request here.

**Comment by rocksdanister** [comment]
Can't change the default configuration since its being used without [issue by many.](https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU)

https://github.com/rocksdanister/lively/blob/b036fd09dde388c0294c6fb86d30b02134188a1a/src/Lively/Lively/Core/Wallpapers/VideoMpvPlayer.cs#L99

Will add `...AppData/Local/Lively Wallpaper/Mpv/portable_config` to the directory list (2nd priority.)
For the time being you can use the installer version of Lively.

**Comment by rocksdanister** [comment]
Docs updated: https://github.com/rocksdanister/lively/wiki/Video-Guide#mpv
