### ISSUE TITLE
I wanted to use a URL with a **m3u8** as well. I can't drag and drop the zip file. Is this a bug?

### ISSUE THREAD

**Issue by cbxk1xg** [rocksdanister/lively#1545]
I wanted to use a URL with a **m3u8** as well. I can't drag and drop the zip file. Is this a bug?

_Originally posted by @cbxk1xg in https://github.com/rocksdanister/lively/issues/341#issuecomment-1400333585_

**Comment by rocksdanister** [comment]
Add youtube-dl since its not included now https://github.com/rocksdanister/lively/issues/1473

Drag'n'drop is recently added to latest version [v2.0.5.0](https://github.com/rocksdanister/lively/tree/v2.0.5.0); it may not work in some conditions like running elevated, just use the filedialog and select the zip instead:
<img width="673" alt="image" src="https://user-images.githubusercontent.com/17554161/215334563-1465f035-9058-4c14-8e0f-0624bbfb9116.png">

**Comment by cbxk1xg** [comment]
Still the same here. I think it's fair to say: It's a bug.

**Comment by rocksdanister** [comment]
> Still the same here. I think it's fair to say: It's a bug.

I don't know what this means here, you are not being clear what the bug is and steps you tried to fix the bug (for example did you try adding it using Open like I suggested and when you did was there any error message etc..)

Fill the issue template with all the details including a video showing the problem:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
