### ISSUE TITLE
lag

### ISSUE THREAD

**Issue by novbucks** [rocksdanister/lively#1563]
Hello, my lively wallpaper is lagging a bit more than I had wanted it to. The engine is low quality (720p or near that) and 15 - 30 fps. If you can show how to change it I would be happy because I couldn't find how to do so. I had put the setting to lite mode for lower end pc's so im not sure if that is the issue but I had also tried to find the setting to turn that off but I just couldn't. Thank you for your help!

**Comment by rocksdanister** [comment]
I need more information, not sure what lag means here.

Fill the issue template:
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
