### ISSUE TITLE
It doesn't generate a preview

### ISSUE THREAD

**Issue by facu-lpda20** [rocksdanister/lively#158]
I donwloaded the programme, I installed it, everything was OK. When I wanto to add a new wallpaper, I drag the file to the programme but it doesn't generate a preview of it. When I click "ok" in order to set it, nothing happens.

![screenshot 92](https://user-images.githubusercontent.com/72533737/95405674-d6910900-08ee-11eb-9f62-3b5c86eecd6b.jpg)

**Comment by rocksdanister** [comment]
Why not complete the issue template?
1. Share the logfile(s)
2. What wallpaper file did you use?
3. Have you tried with other video files? did the included "Eternal Light" wallpaper work?

**Comment by mikart01** [comment]
hey, i have the same issue as him, if i tried to paste a link it give a image but it is for the banner of the page, if i tried a video (MP4) donsent give a preview and i download the videos from this page

**Comment by rocksdanister** [comment]
Please fill this:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file**
Share the log file(s) from Local Appdata folder C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs
