### ISSUE TITLE
YouTube Livestreams Not Working

### ISSUE THREAD

**Issue by DiamondNinjaX** [rocksdanister/lively#1598]
Title, basically. Adding a livestream link as a new wallpaper shows a WallpaperPluginException error.

1. Install Lively (as you would normally)
2. Add wallpaper through Add Wallpaper (as you would normally)
3. Wait a bit/click on the new "watch" wallpaper

Interesting how it's not working now, but in older Lively versions it was. I'm running W10 22H2, specifically OS build 19045.2604 and Windows Feature Experience Pack 120.2212.4190.0.

![image](https://user-images.githubusercontent.com/50220571/221834535-99008599-7831-475a-a3d8-990c46c74312.png)

Log File: 
[lively_log_20230228_190041.zip](https://github.com/rocksdanister/lively/files/10849486/lively_log_20230228_190041.zip)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper#updating-youtube-dl

**Comment by rocksdanister** [comment]
youtube-dl has not been updated in some time so it maybe broken, you can try youtube-dlp which is an up-to-date fork.. if it also fails not much I can do here.

**Comment by DiamondNinjaX** [comment]
Okay, will take a look at it and update you when I do.

**Comment by DiamondNinjaX** [comment]
Sorry for the delay, but I just tried it and it only _half_-worked.

The wallpaper will initialize, but this is the desktop view:
![image](https://user-images.githubusercontent.com/50220571/223076630-4e81cd44-4cbd-4dea-8f51-70eb40202c8f.png)
As previewed in Lively's GUI:
![image](https://user-images.githubusercontent.com/50220571/223079177-7ac0c7f0-b625-4112-840b-3208d3c57128.png)

Note that this applies to all YouTube live-stream wallpapers, and I tested both CefSharp/WebView2.

Is there any fix for this? @rocksdanister

**Comment by rocksdanister** [comment]
Follow the steps properly, its not using yt-dlp and make sure the link is a proper url and not a playlist etc..

No need to ping me on my own repo..

**Comment by DiamondNinjaX** [comment]
Ah, my apologies.

I had youtube-dl.exe named as _youtube-dl.exe_ so it was youtube-dl.exe.exe 🤣
Wiki had me confused, but it's working now. Thanks!

**Comment by angad11121** [comment]
I'm still receiving the above error. Could you please check @DiamondNinjaX?

Upon clicking on the right arrow to add the video : 
![image](https://github.com/rocksdanister/lively/assets/50276105/55277a70-0dd5-4a6d-8342-778ba028a6d4)

It just adds the video without the preview/name-edit dialog box.

When I click on that particular video wallpaper I get the same error as yours: 
![image](https://github.com/rocksdanister/lively/assets/50276105/71e0aacf-25f8-4a01-91be-e6906fbec582)


I'm assuming I'm supposed to install yt-dlp.exe and rename it to youtube-dl.exe because that is the only way "streams" appears in the wallpaper settings.

Here is the same in /Plugins/Mpv/:
![image](https://github.com/rocksdanister/lively/assets/50276105/dfbdfd4f-9e6a-49d2-aa98-2191a2be48f4)

The only other thing left for me to check if it is being caused by a relatively newer version installed by me.
Please do tell me if I understood any step wrong.

Thanks!

-------------------
Update:

Hi again.
It turns out that I was correct about the newer version theory.
I was earlier using [yt-dlp 2023.03.04](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.03.04)  version which was not working until I switched it to [yt-dlp 2023.02.17](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.02.17). 

Sorry for any inconvenience. :)

**Comment by rocksdanister** [comment]
Hmm try updating mpv player and see if newer version works:

https://sourceforge.net/projects/mpv-player-windows/files/32bit/
