### ISSUE TITLE
Command Line Controls for Placement Method

### ISSUE THREAD

**Issue by Odotocodot** [rocksdanister/lively#1599]
Currently you can only read the placement method by diving into the Settings.json file and reading the "WallpaperArrangement" key.

I would love to have the ability to change the placement method for wallpapers via command line!

**Comment by rocksdanister** [comment]
I don't understand 
1. What is placement method? 
2. Give an example of what you are trying to do.

**Comment by Odotocodot** [comment]
Ah sorry this is what I mean:
![image](https://user-images.githubusercontent.com/48138990/221875845-de32caa2-a045-403a-a6be-a7f273b6a620.png)

**Comment by rocksdanister** [comment]
Ah got it, can you give an example why you want to change that through commandline control?

**Comment by Odotocodot** [comment]
Ive created a small plugin that allows me to set wallpapers on monitors among other stuff via a terminal style interface, and I would like to be able to change the placement method as well without showing the lively app.

**Comment by rocksdanister** [comment]
I just had a look, looks like I made the wallpaper adjusting (wallpaper on screen1 spanning to all screens or duplicating etc..) when user changes Placement Method part of the UI program 🤔

https://github.com/rocksdanister/lively/blob/07231e26add55a5f82e970e7be17d41325ff9627/src/Lively/Lively.UI.WinUI/ViewModels/ControlPanelViewModel.cs#L323-L325

Originally wallpapers just cleared when Placement Method was changed by user; later looks like I just added the code in the UI itself to handle it since that's the only place its being changed by user.

This makes things difficult since commandline commands are run by the core program and not UI. One quick solution is just to clear the wallpaper when Placement Method is changed through commandline 🤔

**Comment by Odotocodot** [comment]
Ah I see. Yeah that solution would work, could even just reapply the wallpaper directly afterwards.
