### ISSUE TITLE
HTML forms non writable

### ISSUE THREAD

**Issue by MisterCoder74** [rocksdanister/lively#1715]
**Describe the bug**
If a web page containing text fields  is used as a wallpaper (i.e. customized search engine or sticky note), it is not possible to write inside the form

**To Reproduce**
1. Create a new html page with a form and text field
2. Import it as a wallpaper (locally or remote)
3. select it as wallpaper
4. try to write inside the textfield, it is not allowed, key pressures select icons on desktop

**Expected behavior**
focusing the textfield and writing should add text inside the textfield

**Screenshots/Video**

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro 19044.2965]
- windows standard.

**Additional context**

**Log file (Important)**
No log entry created

**Comment by rocksdanister** [comment]
Only mouse is input forwarded by default for safety (keyloggers) and to avoid desktop icon selection by accident.

Keyboard + mouse can be enabled:
![image](https://github.com/rocksdanister/lively/assets/17554161/48707a2d-68e2-49a0-a827-b65b5c1ba6f5)

**Comment by MisterCoder74** [comment]
thank you very much

**Comment by Ryanjiang2009** [comment]
I think this is not useful, since this isn't a kiosk app.
If you want to do this, maybe adding a kiosk mode is more helpful.
In this mode, the user can interact with the webview and the taskbar is hidden (you can achieve this by simply killing explorer.exe) and add a API for exiting the kiosk mode or to add a hidden area which can trigger the action by double clicking, etc.



At 2023-06-03 04:32:59, "alessandro demontis" ***@***.***> wrote:

thank you very much
