### ISSUE TITLE
Some wallpapers cause high gpu usage.

### ISSUE THREAD

**Issue by LuciusMercier** [rocksdanister/lively#178]
My computer has been acting up and I have identified the problem to be lively wallpaper. 
This is what my task manager looks like without lively running
![image](https://user-images.githubusercontent.com/47582344/97514464-251d4a80-1965-11eb-9b2e-b47cc1f01ee0.png)

This is what it looks like with lively running
![image](https://user-images.githubusercontent.com/47582344/97514516-4847fa00-1965-11eb-9626-d3e88c11e773.png)

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Performance

**Comment by Pauweltje** [comment]
I own a RTX 3080ti and the wallpaper is eating 50 percent! 
Bye bye Wallpaper!

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Performance

>Just a quick note regarding taskmanager: Looking at Taskmanager cpu & gpu usage on the Processes tab can be misleading, because it is a relative measure based on clockspeed of the hardware.
Every cpu & gpu runs at various clockspeed based on performance demand, for example if the gpu is in low performance mode(usually on desktop, clockspeed 300mhz on my gtx 750) the gpu usage will be very high which is still normal & consumes less power.
So high gpu or cpu usage can be due to low clockspeed, better to use utility like gpu-z to observe both clockspeed & usage.
