### ISSUE TITLE
When applying wallpaper nothing happens

### ISSUE THREAD

**Issue by yuskeyoshiro** [rocksdanister/lively#1814]
I downloaded the Lively wallpaper but when I tried to use the wallpaper, nothing happened. It just refreshed. I got no error or anything. I was able to use it, but as a picture. Not an animated wallpaper. I have attached the log file below.
[lively_log_20230728_211912.zip](https://github.com/rocksdanister/lively/files/12196140/lively_log_20230728_211912.zip)
Please solve this issue for me because I tried downloading it again for almost 2 to 3 times but the issue continues.

**Comment by rocksdanister** [comment]
This is usually a sign there is some conflict with software on the system.. do you have any software that modify desktop? stardock fences etc..

**Comment by DavidCF77** [comment]
Hi there,
 I have the same issue plus I was using Push Wallpaper, and it is not working either.
 I can set  wallpaper but cannot get live wallpaper.

Edition	Windows 11 Pro
Version	23H2
Installed on	‎25/‎07/‎2023
OS build	22631.2129
Experience	Windows Feature Experience Pack 1000.22669.1000.0

Is there a setting that can block live wallpaper from working?
Do not know if it is this new version of Windows from the Beta channel that I am on that is causing the problem.
I had not installed any new software that was supposed to change the desktop.
Help Please.

**Comment by rocksdanister** [comment]
Yeah beta versions of Windows tend to break things.

**Comment by eXcalpius** [comment]
The new windows and dev betas break Wallpaper Engine, Lively Wallpaper, and presumably Deskscapes. They added HDR support to still wallpaper backgrounds, so I'm guessing that broke the way these programs access the desktop. Since this is a new feature, it is not likely a bug per se. Either way, these developers should contact Microsoft directly to find out what changed and how they broke it. :(
