### ISSUE TITLE
similar features with dynamic weather like rePaper?

### ISSUE THREAD

**Issue by Rmdhn1** [rocksdanister/lively#183]
since you said this was newer and better and i should probably use this, i visited the page but it doesn't seem like there is any dynamic weather

**Comment by rocksdanister** [comment]
Lively is a software for playing webpages and videos as wallpapers, if you want a particular feature as a wallpaper you can program your own webpage for Lively unlike rePaper which can only do one thing.

I uploaded over 100+ example wallpaper for Lively:
https://www.deviantart.com/livelywallpaper/gallery/

Instead of making each and everyone one of them into individual apps, Lively can handle them all.
