### ISSUE TITLE
setwp doesn't work for html files

### ISSUE THREAD

**Issue by shaylavi** [rocksdanister/lively#1872]
**Describe the bug**
When running the command-line to set the wallpaper and choosing built-in HTML wallpapers, it doesn't work.

**To Reproduce**
1. open command line
2. Execute lively.exe with the parameter to set the wallpaper - setwp --file c:\path\to\file
3. choose an existing HTML based wallpaper

**Expected behavior**
The wallpaper should change to the built-in HTML that was provided in the parameters.. This option works fine for custom video files.

**Desktop (please complete the following information):**
Windows 11

**Additional context**

**Log file (Important)**
[lively_log_20230901_022036.zip](https://github.com/rocksdanister/lively/files/12488236/lively_log_20230901_022036.zip)

**Comment by rocksdanister** [comment]
>Execute lively.exe with the parameter to set the wallpaper - setwp --file c:\path\to\file

Share the full command you used, log is saying its missing argument
`2023-09-01 02:11:46.0788|ERROR|Lively.Automation.CommandHandler|CommandLine.MissingRequiredOptionError`

**Comment by shaylavi-esriau** [comment]
Thank you for the quick reply!
Here's the command I'm using for a video file, which works -
"C:\Program Files\WindowsApps\12030rocksdanister.LivelyWallpaper_1.0.136.0_x86__97hta09mmv6hy\Build\Lively.exe" setwp --file "D:\DynamicBackgrounds\Mountains-003.mp4"

** The extremely long path is because it was installed from MS store - I worked around it and it works (would be good to consider this though for future versions - maybe a separate data/command folder).

Here's the command I'm using for the Matrix HTML canvas background, which doesn't work -
"C:\Program Files\WindowsApps\12030rocksdanister.LivelyWallpaper_1.0.136.0_x86__97hta09mmv6hy\Build\Lively.exe" setwp --file "C:\Users\myuser\AppData\Local\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper\Library\wallpapers\xn0quq52.bq2\index.html"

I also tried without .html, without index.html, with different json files, with subfolders, etc.. 

I also tried to place the Matrix on drive D under a short path but it didn't work.

The error from the log might be a result to one of my countless attempts to change the path.

**Comment by rocksdanister** [comment]
>** The extremely long path is because it was installed from MS store - I worked around it and it works (would be good to consider this though for future versions - maybe a separate data/command folder).

That's what command utility is for:
https://github.com/rocksdanister/lively/wiki/Command-Line-Controls#instruction

**Comment by rocksdanister** [comment]
It's failing because desktop-bridge (store) sandboxing path being different from the actual path, so verification of folder fails.

https://github.com/rocksdanister/lively/blob/9692ec07f3468bd9e337f11f37ce5c36282504ec/src/Lively/Lively/Automation/CommandHandler.cs#L157-L158

Replace `C:\Users\myuser\AppData\Local\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper\Library\wallpapers\xn0quq52.bq2`

with `C:\Users\myuser\AppData\Local\Lively Wallpaper\Library\wallpapers\xn0quq52.bq2`

**Comment by shaylavi** [comment]
I did and it doesn't work - the path you suggested doesn't exist. The one I used does exist - I made sure of that before trying.
I can simply verify this when using the variable %appdata%
EXIST = %AppData%\..\Local\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper\Library\wallpapers\xn0quq52.bq2
DOESNT EXIST = %appdata%\..\Local\Lively Wallpaper\Library\wallpapers\xn0quq52.bq2

** there's a missing slash before the two dots of the path that GitHub escaped. The path is valid.

It might be that the process don't have enough permissions to reach that path or maybe the string is too long for it I don't know.

I am using the command utility (is there another way of doing this?), but the utility is well hidden under the localCache folders as a result of installing it through the windows store.. maybe if the command utility is added to the path automatically, then it can be reached from anywhere

**Comment by shaylavi** [comment]
Following your line of thought, I simplified the path and copied the theme to drive D.. based on this screenshot it doesn't seem to be a path issue -
![2023-09-01 18_38_17-DynamicBackgrounds](https://github.com/rocksdanister/lively/assets/4600500/ae317c6e-1904-4a1b-9289-20ed02c00fdb)


I've attached new logfiles after attempting the new path twice
[lively_log_20230901_184121.zip](https://github.com/rocksdanister/lively/files/12496082/lively_log_20230901_184121.zip)

**Comment by shaylavi** [comment]
Okay problem solved :) I used the debug window to see the right path to be used.
Also, it seems like index.html must be included when pointing to this type of theme.

EXIST BUT WRONG = C:\Users\shayl\AppData\Local\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper\Library\wallpapers\xn0quq52.bq2

DOESN'T EXIST BUT RIGHT = C:\Users\shayl\AppData\Local\Lively Wallpaper\Library\wallpapers\xn0quq52.bq2

so actually that's what you suggested but it was missing the index.html

Thanks for the help! The debug window is brilliant. Now I can make timers for different themes :)

**Comment by shaylavi** [comment]
Okay problem solved :) I used the debug window to see the right path to be used.
Also, it seems like index.html must be included when pointing to this type of theme.

EXIST BUT WRONG = C:\Users\shayl\AppData\Local\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper\Library\wallpapers\xn0quq52.bq2

DOESN'T EXIST BUT RIGHT = C:\Users\shayl\AppData\Local\Lively Wallpaper\Library\wallpapers\xn0quq52.bq2

so actually that's what you suggested but it was missing the index.html

Thanks for the help! The debug window is brilliant. Now I can make timers for different themes :)

**Comment by rocksdanister** [comment]
>I am using the command utility (is there another way of doing this?), but the utility is well hidden under the localCache folders as a result of installing it through the windows store.. maybe if the command utility is added to the path automatically, then it can be reached from anywhere

I don't get you, its a downloaded file and can be added to system path:
https://youtu.be/iEb5DVMz3Ds?si=aBQjDCRToZ8roAmr&t=201

**Comment by shaylavi** [comment]
ah I didn't know that - I haven't seen any tutorials I just installed from the store and tried to work with it
