### ISSUE TITLE
ich kann keine wallpaper hinzufügen

### ISSUE THREAD

**Issue by bennimx9** [rocksdanister/lively#188]
Liebes Lively Team
wenn ich ein Wallpaper als Hintergrund verwenden möchte erscheint ein Fenster (siehe Bild) oder ich ein Wallpaper hinzufügen möchte. Dies geschah nach Installierung ihres neuen Updates über Operagx Browser (Update v1130)
Liebe grüße Bennimx9
![Screenshot 2020-11-07 093544](https://user-images.githubusercontent.com/74093072/98436694-ab602c00-20dd-11eb-9b1a-7f8cd71ce6ef.png)

**Comment by rocksdanister** [comment]
Fill this:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file(Very important)**
Share the log file(s) from Local Appdata folder C:\Users\YourUserName\AppData\Local\Lively Wallpaper\logs

**Comment by MoltenCoreDev** [comment]
Bitte füllen Sie das oben angegebene Formular von rockdanister aus.
Geben Sie auch das Fehlerprotokoll aus dem Verzeichnis frei C:\Users\YourUserName\AppData\Local\Lively Wallpaper\logs

Translated by google translator™
