### ISSUE TITLE
Possible packaging in Chocolatey or WinGet

### ISSUE THREAD

**Issue by ptanmay143** [rocksdanister/lively#199]
**Is your feature request related to a problem? Please describe.**
Having to manually install Lively on every system in a lab environment is tiresome process.

**Describe the solution you'd like**
Having lively packaged as a [Chocolatey](https://github.com/chocolatey-community/chocolatey-package-requests) package.

**Describe alternatives you've considered**
Having lively packaged as a [WinGet](https://github.com/microsoft/winget-pkgs) package.

**Comment by rocksdanister** [comment]
I looked into WinGet in the past and it supports Inno installer.
I am not sure how the Visual C++ Redistributable and .Net core runtime(this require admin access.) will play nicely since its not currently automated and require user interaction to install.

Its possible to make a self contained lively binary so that .net core install can be avoided but currently I am having some issues with the selft contained build and xaml island.

**Comment by rocksdanister** [comment]
**Update**
So I managed to make a self contained version of Lively that require no additional dependency installation (.Net core and VC++)
I had to remove Xaml island(uwp) due to some publishing issues .

Cons:
1. UI is not as smooth as the github version and lacks some visual features (animated gif, smooth scroll etc..)
2. Maintaining two versions of Lively will be annoying.
3. Not as efficient, bit higher memory usage.

Pros:
1. Works on older version of Windows.
2. Should be more stable for people having [issue](https://github.com/rocksdanister/lively/issues/189) with the xaml island version.

**Comment by ptanmay143** [comment]
Maybe you could release this version as a pre-release on GitHub accompanied with a poll and a notice regarding the pros and cons of the new approach.

**Comment by rocksdanister** [comment]
Currently testing Windows store version https://github.com/rocksdanister/lively/issues/9#issuecomment-734229416
Will see how things turns out, I think WinGet supports MSIX package.

**Note:** I will publish it myself when ready, I request you do not publish to third party stores without my permission.

**Comment by rocksdanister** [comment]
Store release is up: https://github.com/rocksdanister/lively/issues/213
