### ISSUE TITLE
Option to disable auto update checking?

### ISSUE THREAD

**Issue by santarl** [rocksdanister/lively#1990]
I don't see an option to disable auto update checking.

It would be nice to have a toggle to disable auto update checking. Thanks.

**Comment by rocksdanister** [comment]
There is no plan to implement this at the moment.

This will make dealing with user support queries difficult and I only provide support for latest version.

**Comment by santarl** [comment]
Why not just add a disclaimer saying that support will not be provided on turning it off?

**Comment by rocksdanister** [comment]
Disclaimer is not useful for big projects, for every person that reads there will be many more who don't or care.. currently I receive support emails, reddit posts/messages and github issue.. people being on older version will create more confusion.

Being updated also helps diagnosing and fixing new issues, this is important because the beta program is not successful.

ps: The Microsoft store version does not show update prompts and will update according to store settings.

**Comment by santarl** [comment]
Awesome, will switch to windows store version. Thanks
