### ISSUE TITLE
Win11 preview version 26XX dynamic wallpaper invalid

### ISSUE THREAD

**Issue by Chenlei534** [rocksdanister/lively#2074]
**Describe the bug**
Win11 preview version 26XX dynamic wallpaper invalid

**To Reproduce**
1. After compiling with the latest code and running it on Win11 preview version 26xx, it was found that the previous modifications to the window hierarchy structure that caused the dynamic wallpaper to become invalid did not take effect。

2. As shown in the picture, the video window has been successfully added, but the dynamic wallpaper is not displayed。
![截图_20240112_191444_226](https://github.com/rocksdanister/lively/assets/20490724/d92b70dc-a2d4-4a95-99c0-6297338dbb18)

**Comment by shangsh** [comment]
I'm also having this problem, and I'm on the 26016 version of win11 and the live wallpaper doesn't come out

**Comment by everything411** [comment]
That is strange, because I'm on 26016 too and it works.

**Comment by rocksdanister** [comment]
Maybe he has Windows HDR turned on?

**Comment by everything411** [comment]
lively works well for me when hdr turned on.

maybe windows widgets? i disabled widgets from group policy. i will have a test later

update: widgets also ok.

so strange

**Comment by Yvonne5531773** [comment]
same issue, any update?

**Comment by rocksdanister** [comment]
@Yvonne5531773 The release build does not have the patch yet, did you try the test build provided here:
https://github.com/rocksdanister/lively/pull/2050#issuecomment-1868241803

**Comment by Yvonne5531773** [comment]
@rocksdanister I have tested the latest build, and it works fine. However, when switching the video player from mpv to Windows Media Foundation (WMF), play fails. I have tried mpv and VLC, and they work correctly, but WMF is not functioning. May I know the reason for this issue?

**Comment by everything411** [comment]
Confirmed that WMF Player is not working properly with the new  window layout, while mpv, vlc, cef and webview2 all work well. I've checked the window styles among these different backends but haven't noticed something suspicious.

**Comment by sergodesit** [comment]
On build 26040.1000 there is a video overlay and does not interact with the desktop.

**Comment by Yvonne5531773** [comment]
@rocksdanister Do you know why WMF doesn't work, but VLC and MPV do? Can you provide specific reasons? Thanks~

**Comment by rocksdanister** [comment]
I don't use Windows insider builds.

**Comment by TheTechWiz5305** [comment]
I'm on Build 26058 and it still isn't fixed

**Comment by rocksdanister** [comment]
Because official release is not updated yet, there is unofficial one https://github.com/rocksdanister/lively/issues/2074#issuecomment-1915328348

Lively does not officially support insider builds since its subject to change too frequently, this issue tracker is open because a user submitted a patch.

**Comment by keshka** [comment]
The issue persists on build 26080.ge_release.240308-1400

**Comment by sergodesit** [comment]
Yes, it is saved.

Отправлено из приложения "Почта<https://go.microsoft.com/fwlink/?LinkId=550986>" для Windows

________________________________
От: Keshka Kotera ***@***.***>
Отправлено: Saturday, March 16, 2024 7:52:55 PM
Кому: rocksdanister/lively ***@***.***>
Копия: sergodesit ***@***.***>; Comment ***@***.***>
Тема: Re: [rocksdanister/lively] Win11 preview version 26XX dynamic wallpaper invalid (Issue #2074)


The issue persists on build 26080.ge_release.240308-1400

**Comment by rocksdanister** [comment]
Got this information from Microsoft:
> As Windows evolves to help deliver the best customer experiences, we have changed how the Background renders in Windows to enable new scenarios such as HDR Backgrounds as announced in Windows Insider.
 
> When the desktop is split out from the list view window (aka the "raised desktop") we no longer create multiple top-level HWNDs to support this scenario. Instead, the top-level "Progman" window is now created with WS_EX_NOREDIRECTIONBITMAP (so there is no GDI content for that window at all) and the shell DefView child window is a WS_EX_LAYERED child window. When the desktop is raised, we create a child WorkerW window that is z-ordered under the DefView that will render the wallpaper. The DefView window will draw mostly transparent with just the icons and text.
 
> If your application forces the "raised desktop" state, it will now need to create its own WS_EX_LAYERED child HWND that is z-ordered under the DefView window but above the WorkerW window. This window should likely be a SetLayeredWindowAttributes(bAlpha=0xFF) window so that you can do DX blt presents to it and not suffer performance issues.

**Comment by amukatov9101** [comment]
In windows pro 11 24H2 Canary channel not working? I have errors and can't install theme

**Comment by sergodesit** [comment]
Live wallpapers do not work on the Canary channel, they are not synchronized with the desktop, on a blank desktop there is just a live picture without the ability to control.

Отправлено из приложения "Почта<https://go.microsoft.com/fwlink/?LinkId=550986>" для Windows

________________________________
От: amukatov9101 ***@***.***>
Отправлено: Monday, April 15, 2024 2:53:30 PM
Кому: rocksdanister/lively ***@***.***>
Копия: sergodesit ***@***.***>; Comment ***@***.***>
Тема: Re: [rocksdanister/lively] Win11 preview version 26XX dynamic wallpaper invalid (Issue #2074)


In windows pro 11 24H2 Canary channel not working? I have errors and can't install theme

**Comment by rocksdanister** [comment]
Yes, the next update (this month) will have the patch.

**Edit:** Update delayed to May.

**Comment by rocksdanister** [comment]
Beta version is available for testing:
https://github.com/rocksdanister/lively-beta/releases

![image](https://github.com/rocksdanister/lively/assets/17554161/c4284e07-c4c6-4c9d-b812-265535bbcbb4)

**Comment by rocksdanister** [comment]
There is an alignment issue with Mpv player (video wallpaper) in 24h2 beta builds:
![image](https://github.com/rocksdanister/lively/assets/17554161/e5cc9a05-6be6-4402-9109-4c719d453e2f)

The issue started happening from Mpv build `2024-03-31` onwards:
https://sourceforge.net/projects/mpv-player-windows/files/64bit/

Switching to the previous build from 2024-03-17 `mpv-x86_64-20240317-git-3afcaeb.7z` fixed the issue:
https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20240317-git-3afcaeb.7z/download

For the time being I have started updating Store version of Lively with this downgraded Mpv player.
Installer version I am waiting to see if there are any other obvious bugs before pushing the update; You can manually copy the mpv player to `<Lively install location>\plugins\mpv` if you can't wait.

Need to investigate the cause and find out what changed in Mpv player or Windows (?.)

**Comment by studiobutter** [comment]
I'm going to comment here since the issue isn't just Lively related. I'm on Release Channel of Windows 11 and 24H2 have release for a while now. With or without certain tweaks like ExplorerPatcher, Microsoft have changed the ability to use Live Wallpaper on 24H2. I tested these 3 programs, and they confirmed to be running but not showing on Desktop, even with and without Administrator privileges.
- Lively Wallpaper (v2.1.0.8)
- Wallpaper Engine - Steam (v2.5.0.28)
- [n0va Desktop](https://n0va.mihoyo.com/#/) (v2.2.1.3)

**Comment by rocksdanister** [comment]
So I modified based on the official response I got from Microsoft but it looks like things are buggy still.. its best to wait a few months before upgrading to 24H2 as it seems it has quite a few bugs (file scanner bug, cannot delete old update files..)

Can you verify something: Make sure desktop icons are visible (rightclick desktop -> Views -> Show desktop icons is enabled) and restarting the wallpaper app fixes the issue?

**Comment by sergodesit** [comment]
I'm currently on build 27723- 24h2, everything works fine, no problems with liveli wallpapers.
________________________________
Від: Dani John ***@***.***>
Надіслано: 12 жовтня 2024 р. 20:22
Кому: rocksdanister/lively ***@***.***>
Копія: sergodesit ***@***.***>; Comment ***@***.***>
Тема: Re: [rocksdanister/lively] Win11 preview version 26XX dynamic wallpaper invalid (Issue #2074)


So I modified based on the official response I got from Microsoft but it looks like things are buggy still.. its best to wait a few months before upgrading to 24H2 as it seems it has quite a few bugs (file scanner bug, cannot delete old update files..)

Can you verify something: Make sure desktop icons are visible (rightclick desktop -> Views -> Show desktop icons is enabled) and restarting the wallpaper app fixes the issue?

**Comment by studiobutter** [comment]
@sergodesit which insider channel are you on rn?

**Comment by sergodesit** [comment]
canary channel latest build
________________________________
Від: Butter ***@***.***>
Надіслано: 13 жовтня 2024 р. 3:36
Кому: rocksdanister/lively ***@***.***>
Копія: sergodesit ***@***.***>; Mention ***@***.***>
Тема: Re: [rocksdanister/lively] Win11 preview version 26XX dynamic wallpaper invalid (Issue #2074)


@sergodesit<https://github.com/sergodesit> which insider channel are you on rn?

**Comment by everything411** [comment]
the alignment issue is only for mpv backend and not for html5 backend

**Comment by rocksdanister** [comment]
Windows update "KB5050009" have the fix it seems, open Windows update settings -> Check for update.
https://support.microsoft.com/topic/january-14-2025-kb5050009-os-build-26100-2894-bdbfb097-ea20-487d-9171-718d15e26f1b

**Comment by sergodesit** [comment]
I use 27774.1000 (canary), I haven't noticed any problems
________________________________
Від: Dani John ***@***.***>
Надіслано: 18 січня 2025 р. 1:03
Кому: rocksdanister/lively ***@***.***>
Копія: sergodesit ***@***.***>; Mention ***@***.***>
Тема: Re: [rocksdanister/lively] Win11 preview version 26XX dynamic wallpaper invalid (Issue #2074)


Windows update "KB5050009" have the fix it seems, open Windows update settings -> Check for update.
https://support.microsoft.com/topic/january-14-2025-kb5050009-os-build-26100-2894-bdbfb097-ea20-487d-9171-718d15e26f1b

**Comment by jensroth-git** [comment]
Have the same issue right now, I believe it is actually not related to the method of reparenting to the WorkerW correctly, 
but instead to the application you are trying to reparent, 
WMF doesn't work, MPV does, I tried the exact same method on a bunch of different applications as well, 
Chrome works, default WPF apps do not...
maybe its a certain window message that needs to be handled specially etc. 

does anyone have any insights?

**Comment by rocksdanister** [comment]
I think its a window style issue - WPF also stopped but WinForms is fine

> Got this information from Microsoft:
> 
> > As Windows evolves to help deliver the best customer experiences, we have changed how the Background renders in Windows to enable new scenarios such as HDR Backgrounds as announced in Windows Insider.
> 
> > When the desktop is split out from the list view window (aka the "raised desktop") we no longer create multiple top-level HWNDs to support this scenario. Instead, the top-level "Progman" window is now created with WS_EX_NOREDIRECTIONBITMAP (so there is no GDI content for that window at all) and the shell DefView child window is a WS_EX_LAYERED child window. When the desktop is raised, we create a child WorkerW window that is z-ordered under the DefView that will render the wallpaper. The DefView window will draw mostly transparent with just the icons and text.
> 
> > If your application forces the "raised desktop" state, it will now need to create its own WS_EX_LAYERED child HWND that is z-ordered under the DefView window but above the WorkerW window. This window should likely be a SetLayeredWindowAttributes(bAlpha=0xFF) window so that you can do DX blt presents to it and not suffer performance issues.

**Comment by WinExperiments** [comment]
I am working on a desktop replacement as well. It seems that Microsoft removed Program Manager's message 0x052C because it worked on anything except 24H2.

**Comment by reinerrefeld** [comment]
hello.

I don't use Lively but I can bring up some light in this, as I'm a unity developer having the same issue with my LWP app.

**The 0x052C api call still works in 24h2**. The reason why it is not working is because of the default desktop hierarchy has changed in 24h2.
People tend to:
> find Progman as child of Desktop
> find Shelldll_def_view as child of progman
> **find WorkerW as child of Shelldll_def_view** (fails on windows 11 24h2 due to WorkerW is no longer a child of Shelldll_def_view)

Instead, WorkerW appars as child of progman.
You only need to update your enumerators according to this (if that's the method you are using)

You can use the code below (c#) as an example, it works for W10 as well as W11 24h2 and later (currently)
This isn't very professional, as we don't compare anything else (e.g it will eventuall conflict with other apps doing the same or trying to access the original workerW), but I have tested it on Windows 10 and Windows 11 24h2 and it works without anyhting else.

this should spawn an empty WorkerW as child of Desktop using 0x052C api message, and get the WorkerW of the application, that you then can parent to the spawned WorkerW later on.


```
private const string PROGMAN = "Progman";
private const string WORKERW = "WorkerW";
private const string SHELLDLL_DEF_VIEW = "SHELLDLL_DefView";
private const uint SMTO_NORMAL = 0x0; //Send message timeout

public static IntPtr WorkerWHandle
        get {
            	var progman = User32.FindWindow(PROGMAN, null);
            	var workerw = IntPtr.Zero;
            	var shellPtr = IntPtr.Zero;
            	var result = IntPtr.Zero;

		var windowEnumerator = new EnumWindowsProc((tophandle, topparamhandle) => {
    		shellPtr = User32.FindWindowEx(tophandle, IntPtr.Zero, SHELLDLL_DEF_VIEW, IntPtr.Zero);

    		if (shellPtr != IntPtr.Zero) {
                        // if 24h2, get WorkerW as child of progman
       			workerw = User32.FindWindowEx(tophandle, IntPtr.Zero, WORKERW, IntPtr.Zero);  

                        // if fails, assuming older Win11 or 10, get WorkerW as child of shelldll_def_view
        		if (workerw == IntPtr.Zero)
           		workerw = User32.FindWindowEx(IntPtr.Zero, tophandle, WORKERW, IntPtr.Zero);

        		return false; // STOP looping — we found what we want
    		}

    		return true; // KEEP looping
		});

            	User32.SendMessageTimeout(progman, 0x052C, IntPtr.Zero, IntPtr.Zero, SMTO_NORMAL, 10000, out result);
            	User32.ThrowLastError();
            	User32.EnumWindows(windowEnumerator, IntPtr.Zero);
            	User32.ThrowLastError();

            	if(workerw == IntPtr.Zero)
                	throw new Exception("Could not find WorkerW handle");
            		return workerw;
        }
}
```

**Comment by jensroth-git** [comment]
ok, I was finally able to properly fix this issue comprehensively for my library ([RaylibLiveWallpaper](https://github.com/jensroth-git/RaylibLiveWallpaper)), and created a guide for anyone running into the same issue.

# Adapting C++ Live‑Wallpaper Apps to Windows 11 24H2

A practical, framework‑agnostic guide to restoring live desktop wallpaper functionality after the compositor changes in Windows 11 24H2.

---

## 1  Why things broke

Windows 11 24H2 moved all desktop composition into the **Program Manager (Progman)** window hierarchy and replaced the old top‑level *WorkerW* trick with child layered windows. Any app that still tries to embed a top‑level window behind icons will now render *above* or *below* everything unexpectedly. The fix is to inject **your own layered child window** directly into *Progman* between the icon layer and the system wallpaper layer.

## 2  Desktop window stack (24H2)

```
Progman ─┐
         ├─ ShellDLL_DefView  // ListView with desktop icons (interactive, visible)
         ├─ <YOUR LAYERED WINDOW>  // Your custom rendering surface
         └─ WorkerW           // Static wallpaper image (replaced by system)
```

## 3  Core strategy (TL;DR)

1. Ensure the desktop is in its **“raised”** state by sending `0x052C` to *Progman*.
2. Discover handles for:
   - `HWND hProgman   = FindWindow(L"Progman", nullptr);`
   - `HWND hShellView = FindShellDefView(hProgman);`
   - `HWND hWorkerW   = FindWorkerW(hProgman);`
3. Create *or* adopt your app’s rendering window with `WS_EX_LAYERED` and make it fully opaque (`SetLayeredWindowAttributes(..., 255, LWA_ALPHA)`).
4. Re‑parent that window to `hProgman` (`SetParent`).
5. Insert it just **below** the icon window (`SetWindowPos(hLiveWP, hShellView, …)`).
6. Push the WorkerW **behind** it (`SetWindowPos(hWorkerW, hLiveWP, …)`).

That’s all: every frame your renderer draws directly into its layered child, and Windows composites the final desktop.

## 4  Minimal C++ recipe

```cpp
// 1) Prep desktop
HWND hProgman = FindWindow(L"Progman", nullptr);
SendMessageTimeout(hProgman, 0x052C, 0, 0, SMTO_NORMAL, 100, nullptr);

// 2) Locate key children (helper functions left to reader)
HWND hShellView = FindShellDefView(hProgman);
HWND hWorkerW   = FindWorkerW(hProgman);

// 3) Build / reuse your off‑screen rendering window
DWORD ex = WS_EX_LAYERED | WS_EX_NOACTIVATE; // add other styles as needed
HWND hLiveWP = CreateWindowEx(
    ex,
    L"LiveWPClass", L"",
    WS_CHILD,
    0, 0, desktopW, desktopH,
    hProgman, nullptr, hInst, nullptr);

SetLayeredWindowAttributes(hLiveWP, 0, 255, LWA_ALPHA);

// 4) Z‑order choreography
SetWindowPos(hLiveWP, hShellView, 0,0,0,0,
             SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE);
SetWindowPos(hWorkerW, hLiveWP, 0,0,0,0,
             SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE);

ShowWindow(hLiveWP, SW_SHOW); // start rendering
```

**Notes**

- `FindShellDefView` / `FindWorkerW` can be simple tree walks (`EnumChildWindows`).
- Any rendering backend—DirectX, OpenGL, Vulkan, Skia, etc.—works; just target the window handle above.
- Remove `WS_EX_APPWINDOW` if you don’t want a task‑bar entry.
- `desktopW` and `desktopH` refer to the full dimensions of the virtual desktop (e.g., from `GetSystemMetrics(SM_CXVIRTUALSCREEN)`).

## 5  Multi‑monitor options

- **Single huge window** spanning the virtual desktop → simplest, one swap‑chain.
- **One window per monitor** → gives per‑screen content, but manage multiple contexts. Each is still a sibling under *Progman*; apply the same Z‑order rules.

## 6  Keeping Z‑order stable

Theme changes, wallpaper transitions, or virtual‑desktop switches can recreate *WorkerW*. A lightweight timer or event hook that periodically verifies `IsWindowBelow(hWorkerW, hLiveWP)` and reapplies `SetWindowPos` keeps your layer in place. You can use `SetTimer` or `RegisterShellHookWindow` + `WM_SHELLHOOKMESSAGE` to detect changes.

## 7  Troubleshooting checklist

| Symptom                      | Likely cause                                       | Remedy                     |
| ---------------------------- | -------------------------------------------------- | -------------------------- |
| Live wallpaper never appears | Window lacks `WS_EX_LAYERED` or remains top‑level  | Add style & re‑parent      |
| Content transparent          | Forgot `SetLayeredWindowAttributes` or alpha ≠ 255 | Set to 255                 |
| Icons disappear              | You inadvertently raised `ShellDLL_DefView`        | Check `SetWindowPos` order |
| Flicker after theme change   | WorkerW recreated above you                        | Re‑run Z‑order routine     |

**Comment by Zhoros** [comment]
> ok, I was finally able to properly fix this issue comprehensively for my library ([RaylibLiveWallpaper](https://github.com/jensroth-git/RaylibLiveWallpaper)), and created a guide for anyone running into the same issue.
> 
> # Adapting C++ Live‑Wallpaper Apps to Windows 11 24H2
> A practical, framework‑agnostic guide to restoring live desktop wallpaper functionality after the compositor changes in Windows 11 24H2.
> 
> ## 1  Why things broke
> Windows 11 24H2 moved all desktop composition into the **Program Manager (Progman)** window hierarchy and replaced the old top‑level _WorkerW_ trick with child layered windows. Any app that still tries to embed a top‑level window behind icons will now render _above_ or _below_ everything unexpectedly. The fix is to inject **your own layered child window** directly into _Progman_ between the icon layer and the system wallpaper layer.
> 
> ## 2  Desktop window stack (24H2)
> ```
> Progman ─┐
>          ├─ ShellDLL_DefView  // ListView with desktop icons (interactive, visible)
>          ├─ <YOUR LAYERED WINDOW>  // Your custom rendering surface
>          └─ WorkerW           // Static wallpaper image (replaced by system)
> ```
> 
> ## 3  Core strategy (TL;DR)
> 1. Ensure the desktop is in its **“raised”** state by sending `0x052C` to _Progman_.
> 2. Discover handles for:
>    
>    * `HWND hProgman   = FindWindow(L"Progman", nullptr);`
>    * `HWND hShellView = FindShellDefView(hProgman);`
>    * `HWND hWorkerW   = FindWorkerW(hProgman);`
> 3. Create _or_ adopt your app’s rendering window with `WS_EX_LAYERED` and make it fully opaque (`SetLayeredWindowAttributes(..., 255, LWA_ALPHA)`).
> 4. Re‑parent that window to `hProgman` (`SetParent`).
> 5. Insert it just **below** the icon window (`SetWindowPos(hLiveWP, hShellView, …)`).
> 6. Push the WorkerW **behind** it (`SetWindowPos(hWorkerW, hLiveWP, …)`).
> 
> That’s all: every frame your renderer draws directly into its layered child, and Windows composites the final desktop.
> 
> ## 4  Minimal C++ recipe
> // 1) Prep desktop
> HWND hProgman = FindWindow(L"Progman", nullptr);
> SendMessageTimeout(hProgman, 0x052C, 0, 0, SMTO_NORMAL, 100, nullptr);
> 
> // 2) Locate key children (helper functions left to reader)
> HWND hShellView = FindShellDefView(hProgman);
> HWND hWorkerW   = FindWorkerW(hProgman);
> 
> // 3) Build / reuse your off‑screen rendering window
> DWORD ex = WS_EX_LAYERED | WS_EX_NOACTIVATE; // add other styles as needed
> HWND hLiveWP = CreateWindowEx(
>     ex,
>     L"LiveWPClass", L"",
>     WS_CHILD,
>     0, 0, desktopW, desktopH,
>     hProgman, nullptr, hInst, nullptr);
> 
> SetLayeredWindowAttributes(hLiveWP, 0, 255, LWA_ALPHA);
> 
> // 4) Z‑order choreography
> SetWindowPos(hLiveWP, hShellView, 0,0,0,0,
>              SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE);
> SetWindowPos(hWorkerW, hLiveWP, 0,0,0,0,
>              SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE);
> 
> ShowWindow(hLiveWP, SW_SHOW); // start rendering
> **Notes**
> 
> * `FindShellDefView` / `FindWorkerW` can be simple tree walks (`EnumChildWindows`).
> * Any rendering backend—DirectX, OpenGL, Vulkan, Skia, etc.—works; just target the window handle above.
> * Remove `WS_EX_APPWINDOW` if you don’t want a task‑bar entry.
> * `desktopW` and `desktopH` refer to the full dimensions of the virtual desktop (e.g., from `GetSystemMetrics(SM_CXVIRTUALSCREEN)`).
> 
> ## 5  Multi‑monitor options
> * **Single huge window** spanning the virtual desktop → simplest, one swap‑chain.
> * **One window per monitor** → gives per‑screen content, but manage multiple contexts. Each is still a sibling under _Progman_; apply the same Z‑order rules.
> 
> ## 6  Keeping Z‑order stable
> Theme changes, wallpaper transitions, or virtual‑desktop switches can recreate _WorkerW_. A lightweight timer or event hook that periodically verifies `IsWindowBelow(hWorkerW, hLiveWP)` and reapplies `SetWindowPos` keeps your layer in place. You can use `SetTimer` or `RegisterShellHookWindow` + `WM_SHELLHOOKMESSAGE` to detect changes.
> 
> ## 7  Troubleshooting checklist
> Symptom	Likely cause	Remedy
> Live wallpaper never appears	Window lacks `WS_EX_LAYERED` or remains top‑level	Add style & re‑parent
> Content transparent	Forgot `SetLayeredWindowAttributes` or alpha ≠ 255	Set to 255
> Icons disappear	You inadvertently raised `ShellDLL_DefView`	Check `SetWindowPos` order
> Flicker after theme change	WorkerW recreated above you	Re‑run Z‑order routine

Just opened an issue in your repo, can you take a look at it? Thanks

**Comment by rocksdanister** [comment]
Thanks for the contribution, I have had help from Microsoft developer with this issue and I'm posting some of the relevant information for reference:

> Q. In the Lively beta release I am checking progman for
> WS_EX_NOREDIRECTIONBITMAP style and change the way wallpapers are
> applied (In-between ShellDLL and WorkerW with the correct styles)
> based on this Microsoft response I have received in the past.
> 
> A. The "raised desktop" state where the DefView is a child layered
> window is the default state for builds >= 26100. However the DefView
> does not render with transparency today unless you have HDR enabled on
> the system or there is a slideshow animation going (which are
> sometimes broken).
> 
> Starting in the upcoming 27XXX build number releases the DefView will
> always render mostly transparent, eliminating your need to do the
> SendMessage() stuff to force it to be transparent. Sending the messge
> should be ok even on those builds.
> 
> So short answer is looking for WS_EX_NOREDIRECTIONBITMAP is the
> easiest way to know you should be using a correctly z-ordered layered
> child window.
