### ISSUE TITLE
Screen flickering for certain wallpapers

### ISSUE THREAD

**Issue by MuntasirSZN** [rocksdanister/lively#2198]
Screen is flickering for this two wallpapers:

[removed]

Here are the log files:
[lively_log_20240416_185421.zip](https://github.com/rocksdanister/lively/files/14997026/lively_log_20240416_185421.zip)

I use only one picture in the background.It occurs when I use those.Here are the wallapapers:

[removed]

Try the wallpapers yourself to reproduce.

**Comment by rocksdanister** [comment]
Don't share anything other than log files here (example copyrighted videos, binary files ..etc)

Flickering could be due to multiple reasons, things to try:
1. Disable GPU decode for video player.
2. Re-encoding the video using handbreak.
3. Check to see if the flickering is present in video file.
4. Update gpu drivers.

If the problem persists and the flickering is present when playing with mpv video player outside of Lively then file a bug report directly to mpv devs.
