### ISSUE TITLE
Span wallpaper paused when only one monitor is obscured

### ISSUE THREAD

**Issue by DeltaF1** [rocksdanister/lively#22]
## Environment
I have a wallpaper loaded on Span mode. 
## Expected behaviour
When I full-screen an app on one monitor the wallpaper should continue to play in the background.
## Actual Behaviour
When I full-screen an app on one monitor the wallpaper pauses on the other monitor as well and goes black (see #20). Moving focus to the empty monitor by clicking on the desktop or a window causes the wallpaper to resume until focus returns to the full-screen app.

![image](https://user-images.githubusercontent.com/6278108/75120251-308ed800-5658-11ea-9770-25f4ea17102f.png)

**Comment by rocksdanister** [comment]
This is how its currently [designed.](https://github.com/rocksdanister/lively/blob/8ab700f1207838fac8012692c6e1efaf5c5a5a55/src/livelywpf/livelywpf/wp_lib/SetupDesktop.cs#L1809) 

How else checking foreground app and determine when to pause, single foreground app won't maximise across both displays simultaneously

Could get around this by using all process algorithm but currently disabled it due to issues on multiscreen.

**Comment by rocksdanister** [comment]
I changed the behavior in the latest dev build: https://github.com/rocksdanister/lively/commit/51dd077c6ae72ae1926dec0ca987763e26f17b6b

```
- Only pause wallpaper if foreground application is stretched across all displays when "Per Display" setting.
- Pause wallpaper if foreground application is maximised in any monitor when "All Display(s)" setting is selected.
```

Next stable release will have this change.

**Comment by rocksdanister** [comment]
Done, Lively v0.9: https://github.com/rocksdanister/lively/releases/tag/v0.9.0.0
