### ISSUE TITLE
Program doesent want to set my html walpaper

### ISSUE THREAD

**Issue by saraysxroom** [rocksdanister/lively#2225]
**Describe the bug**
after putting html file, program refuses to install any walpaper
**To Reproduce**
1. Open app
2. add walpaper and select file that i pinned
3. dun

**Expected behavior**
walpaper should be set
**Screenshots/Video**
![Снимок экрана 2024-05-07 224447](https://github.com/rocksdanister/lively/assets/118358799/90b76248-bd07-4efa-89c3-aa90e9e9e993)

**Desktop (please complete the following information):**
 - OS: win11
- Which wallpaper was running at the time if any.

**Additional context**
[removed]
(pinned file)

**Log file (Important)**

[lively_log_20240507_224233.zip](https://github.com/rocksdanister/lively/files/15240152/lively_log_20240507_224233.zip)

**Comment by rocksdanister** [comment]
Its likely the project structure, the html file alone is 10.2MB which is causing some issue with CefSharp.

I would refactor it and split it into separate files and try again.

The exception being thrown by CefSharp:
`System.UriFormatException: 'Invalid URI: The hostname could not be parsed.'`

This could be due to the converted nature of the page.
