### ISSUE TITLE
Exception: Exception error repeatedly happening with any background.

### ISSUE THREAD

**Issue by saketchopra** [rocksdanister/lively#2253]
**Describe the bug**
I use clear taskbar to see my desktop background as I use Fluids and I like to see it just pop out but, I noticed that there was nothing in my taskbar therefore, when I opened the app, it said this error again and again with any type of wallpaper `Exception:
Exception`

**To Reproduce**
1. I don't know how to reproduce this behaviour.

**Expected behavior**
I expected it to restart the console and then again work instead, it stopped working a LOT MORE.

**Screenshots/Video**

https://github.com/rocksdanister/lively/assets/17554161/8cbd85da-06e2-493d-8f43-d890d8acd350

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Home
- Fluid

**Additional context**
Not really...

**Log file (Important)**
[lively_log_20240528_181017.zip](https://github.com/rocksdanister/lively/files/15472422/lively_log_20240528_181017.zip)

**Comment by rocksdanister** [comment]
The wallpaper player is crashing, two possibilities I can think of:
1. Something is messing with Lively files. If you have any third party anti-virus software it may have deleted its files due to false flag.. check quarantine.
2. Visual C++ dependency is missing, try installing: https://github.com/rocksdanister/lively/wiki/Common-Problems#somewebpage-wallpapers-are-not-working
