### ISSUE TITLE
Wrong fullscreen scaling of videos

### ISSUE THREAD

**Issue by Cris--** [rocksdanister/lively#2261]
Hi,

i get wrong scaling of videos, doesn't matter with or without the stretch option or which resolution the videos have.

Latest Lively 2.1.0.8 (problem exist since 2.1.x.x or after updating Windows to 24H2 preview).
Lively videoplayer mpv

Windows Pro 24H2 build 26100.712

FullHD Display ( 1920x1080 ) with no Windows display scaling.

Without the Lively scaling feature: 
![Screenshot 2024-06-02 191444](https://github.com/rocksdanister/lively/assets/7994691/8fe40c02-ca13-4170-a88b-8f8762b1e622)

With the Lively scaling feature: 
![Screenshot 2024-06-02 191537](https://github.com/rocksdanister/lively/assets/7994691/72c5b40b-78e7-4fa3-8d30-62f5a3b7016a)

**Comment by Cris--** [comment]
Ahh, sry, searched but didn't found something like this behavior.

**Comment by rocksdanister** [comment]
Its not that exactly, I am not taking insider bug reports at the moment.

Its listed in the changelog:
> Upgrades have been implemented to ensure compatibility with the upcoming Windows 11 24H2 release.
These enhancements are expected to function with insider versions of Windows; however, please note that insider builds are not officially supported.

I have one thread open but will have to test on 24h2 more but my virtual machine is really slow.

**Comment by Cris--** [comment]
I tested on 24H2 Preview/Retail version. Not beta or dev. 
Anyway, take your time!

**Comment by rocksdanister** [comment]
The wording could be more clearer, basically I cant use test channels on my only system due to stability so I tried virtual machine but its too slow and irritating to use.

This issue seems to only happen with video wallpapers using the latest Mpv player, using the old version from 2023-10-08 `mpv-i686-20231008-git-78719c1.7z` don't have this problem:
https://sourceforge.net/projects/mpv-player-windows/files/32bit/

You just need to replace the Mpv files in the Plugins folder (only possible in installer version of Lively.)
