### ISSUE TITLE
Wallpaper not loading

### ISSUE THREAD

**Issue by hadeslmao** [rocksdanister/lively#234]
I have 2 monitors. the first one is 1920x1200 and the second one is 1920x1080. when I close the 1920x1200 and open it back, the wallpaper isnt there anymore and its the default windows wallpaper. But when I close the 1920x1080 one and open it back, the wallpaper is still there. What should I do?

**Comment by rocksdanister** [comment]
1. What do you mean by close and open it back?
2. What display connector are the monitors using?

**Comment by hadeslmao** [comment]
I mean when I close the monitor (turn it off using the button under it) and I am not sure but I think they are connected with HDMI

**Comment by rocksdanister** [comment]
> I am not sure but I think they are connected with HDMI

Check and tell the connectors used by both monitors.

**Comment by kgskgs** [comment]
This happens to me too. The main monitor keeps the wallpaper and uses HDMI, the second monitor loses the wallpaper uses a display port (graphics card) to hdmi (monitor) cable. (Both monitors are 1080p)

**Comment by rocksdanister** [comment]
Yeah, displayport has plug and play feature... it physically disconnects from the computer when shutdown/turned off.
Honestly I never understood this use-case in desktop, if you have a different connector use it.
Currently Lively algorithm is set to remove the wallpaper when monitor is disconnected.

You can find discussions online:
https://www.reddit.com/r/nvidia/comments/66opvp/this_displayport_hotplug_madness_finally_needs_to/

I'm closing this issue for the time being since its beyond me.
I do have some other algorithm planned https://github.com/rocksdanister/lively/issues/25 but its on halt for the time being.

**Comment by kgskgs** [comment]
wouldn't it make sense to apply the wallpaper to a new monitor when it is plugged in (or have an option for that)

**Comment by rocksdanister** [comment]
If there was a unique way to identify monitors sure, the issue I linked talked about it briefly.

Multimonitor support from both gpu vendors and Microsoft side is so so at the moment.
