### ISSUE TITLE
How To Get Lively Screensaver On Windows 11?

### ISSUE THREAD

**Issue by agent-nay** [rocksdanister/lively#2498]
I have tried the description on the screensaver page, downloaded the file but the 'lively' option isnt showing and when i open lively it says i need one-time setup.
![image_2024-11-30_205713927](https://github.com/user-attachments/assets/c228e3d4-b628-4863-9732-050a58b6f06f)
![image_2024-11-30_205801189](https://github.com/user-attachments/assets/11044030-b0a0-4046-ac3d-3b0363cb6040)
![image_2024-11-30_205826682](https://github.com/user-attachments/assets/4087a071-388e-46f7-b37a-af0d6ad99416)

**Comment by CrimsonBlade32** [comment]
I'm having the same issue! I've un-installed, re-installed, and restarted my computer so many times now..I've lost count! The live wallpaper feature works amazing, and the "screensaver" will start when it's supposed to, but i have no access to the "screensaver" tab inside the app, so i can't change or customize anything. It just turns my current wallpaper into a screensaver. Hopefully someone can help us out! I'm not super familiar with coding and all that, but i'm willing to learn!

**Comment by rocksdanister** [comment]
Since its not appearing in Windows screensaver settings, are you sure you right-click installed the file after copying to the system folder?

dup: https://github.com/rocksdanister/lively/issues/2442#issuecomment-2473885159

**Comment by CrimsonBlade32** [comment]
I fixed it! I download from the github site this time instead of the Microsoft store. Also at some point in the install process, i swear it was saying to put the file in "C:\Windows\System32". I installed it in just the "C:\Windows" and it's working perfectly now! In my screensaver settings, "Lively" was always populating as an option, i was just having issues when i went back into the lively APP, and not being able to use the screen saver tab. All working great now! Thanks to the creator of this app and everyone here that helps the ignorant with their issues, you guys and gals rock!
