### ISSUE TITLE
[Feature Request] Change Hue/Saturation/etc for Videos automatically based on external conditions

### ISSUE THREAD

**Issue by Eirakkun** [rocksdanister/lively#254]
Hey there,

I'm finding Lively to so far be a very well sorted out Wallpaper Engine with multiple options and customizations - at a relatively low performance cost (and good general stability).

That said, I do have an idea for an additional feature. Considering it already does Saturation/Hue/Brightness changes to videos played as "Live" wallpapers (through MPV), could it be done as such that specific colour changes be applied according to external conditions? i.e, Time, Being connected to AC Power/Battery, Battery Level?

A use case for this would be a video screensaver changing its hue/brightness/saturation at a given preset time (to simulate changes in external lighting). Or losing saturation at preset steps tied to battery levels. Or lowering darkness to a preset level when disconnected from AC power (while keeping it paused).

An alternative to this is simply to be able to set Lively to automatically apply different wallpapers under different external conditions (Time, Being connected to AC Power/Battery, Battery Level etc), in which case I can edit the video file used by myself and just make multiple different versions of it (or use completely different videos) for use under different conditions.

Or even more simply, make it possible to call the Lively executable to be able to set specific video wallpapers via commandline - in which case I can just leave the task of automating changes through Window's own Task Scheduler.

(Similarly, the option for Lively wallpapers to "fade in" when loaded - or "fade out/fade in" when changed - will be helpful here to minimize jarring transitions between automated changes, but this is another addition altogether that is not as much a priority)

The existing pause when on AC power is already very helpful, both from a power consumption perspective and from an indicative one. The changes I am suggesting above should enchance Lively's ability to indicate external conditions - creating a viable passive means to discern changes at a glance.

However, I am not innately aware of the resource or performance cost (not to mention the programming complexity) involved in making this changes, so I will have to leave the implementation these changes to your decision.

**Comment by rocksdanister** [comment]
Hi, thanks for creating detailed issue.

> That said, I do have an idea for an additional feature. Considering it already does Saturation/Hue/Brightness changes to videos played as "Live" wallpapers (through MPV), could it be done as such that specific colour changes be applied according to external conditions? i.e, Time, Being connected to AC Power/Battery, Battery Level?

This won't be possible because:
The Saturation/Hue/Brightness .. etc are not hard coded and Lively is not aware what they exactly do because they are **user  programmable.**

I didn't write the documentation for it yet, basically it is using the same [Lively Properties API for webpages](https://github.com/rocksdanister/lively/wiki/Web-Guide-IV-:-Interaction) with some changes.
If you make a new LivelyProperties file with [mpv commands](https://mpv.io/manual/master/) and hit refresh you can add your own properties: [DEMO](https://youtu.be/D4nNTRhvOr0?t=14)
By default if no file is present Lively uses a default properties file for video wallpapers.

>An alternative to this is simply to be able to set Lively to automatically apply different wallpapers under different external conditions (Time, Being connected to AC Power/Battery, Battery Level etc), in which case I can edit the video file used by myself and just make multiple different versions of it (or use completely different videos) for use under different conditions.

Playlist is planned: https://github.com/rocksdanister/lively/issues/137

> Or even more simply, make it possible to call the Lively executable to be able to set specific video wallpapers via commandline - in which case I can just leave the task of automating changes through Window's own Task Scheduler.

Commandline support is planned: https://github.com/rocksdanister/lively/issues/61

I'm closing this issue, you can follow the existing discussions listed for the features asked.
