### ISSUE TITLE
Running fullscreen games at non-native resolution misalign wallpaper in multiple monitor system.

### ISSUE THREAD

**Issue by bruhmomentumXXX** [rocksdanister/lively#256]
Without CSGO open: 
![Annotation 2020-12-30 211511](https://user-images.githubusercontent.com/70071828/103390869-a66b9780-4ae4-11eb-9e8d-1a460bc47784.png)
With CSGO open:
![20201230_211611](https://user-images.githubusercontent.com/70071828/103390874-aec3d280-4ae4-11eb-8442-7ecc436b65d3.jpg)
second photo taken with my phone excuse the poor quality

**Comment by rocksdanister** [comment]
After you close the game, it returns to normal right?

**Comment by bruhmomentumXXX** [comment]
> After you close the game, it returns to normal right?

yes

**Comment by bruhmomentumXXX** [comment]
yes

**Comment by rocksdanister** [comment]
Yes, I'm only updating the size of the wallpaper and not the position when screen resolution change (in this case csgo fullscreen mode) because of a bug.

Will be fixed later, if you want as a temporary solution you can run the game in window mode or run the game at native resolution fullscreen mode.

**Comment by bruhmomentumXXX** [comment]
ok
