### ISSUE TITLE
Batch Live wallpaper addition feature (like multiple .mp4)

### ISSUE THREAD

**Issue by S4NSKAR** [rocksdanister/lively#273]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have a lot of videos to add to the library (like 50-100s) but the library supports a maximum of only 1 file at a time.

**Describe the solution you'd like**
=> Allow to drag and drop multiple video files into the library instead of only 1
=> Optionally, an option to allow setting "Video Libraries folder" which would automatically fetch all supported video files from there and allow to set a playlist

**Describe alternatives you've considered**
There is no alternative I could think of as of now. Forced to add video manually :(

**Additional context**
_Removed Link_
Their own software is very lightweight (few MBs) but lacks reliability. But it has few features like Adding custom music, Adding Automatic wallpaper changing frequency, etc that might inspire this project. Maybe a collaboration.

**Comment by rocksdanister** [comment]
>I'm always frustrated when I have a lot of videos to add to the library (like 50-100s) but the library supports a maximum of only 1 file at a time.

Lively sets the wallpaper window into a smaller library import window and screen records that region to generate preview gif and thumbnail image; this method works across all wallpaper types -  video, webpages, separate executables etc..
Obviously for this reason import is restricted to one file at a time.

Few solutions I can think of:
1. One approach would be to use ffmpeg to create the preview clips but then this will only work for video wallpapers and then there is the added application size increase bundling ffmpeg (~60mb)
2. Another approach would be to skip the preview clips and thumbnail all together, but that will make the library ugly - one approach would be to create the thumbnail during wallpaper playback but unfortunately the code did not work for me https://github.com/rocksdanister/lively/issues/150

>There is no alternative I could think of as of now. Forced to add video manually :(

You can put them into separate folders and make livelyinfo.json file manually in `Library\wallpapers` if you prefer.

>Their own software is very lightweight (few MBs) but lacks reliability.

Lively ships its own custom web browser(based on chromium) and videoplayer (based on mpv player) which increases the size.
Lively supports multiple wallpaper players (main app and wallpaper players are separate programs) and webview implementation is under work which has the potential to reduce appsize in the future.

At the core of it windows is doing all the work and that app is likely using windows media player which Lively also supports under videoplayer settings. 
Honestly if size is a concern and only video wallpapers are required then my software might not be best fit for you.
You can try alternatives like: 
https://github.com/Francesco149/weebp

>Adding Automatic wallpaper changing frequency, etc that might inspire this project. Maybe a collaboration.

I don't really understand what you mean by collaboration, its a closed source software right?

[Playlist](https://github.com/rocksdanister/lively/issues/137) is coming soon, unfortunately due to the complications that arise from many wallpaper types Lively supports and there only being one person working on this project - adding new features like this properly supporting everything takes time.

_(I removed the link in original comment because their hosting stolen work with no credit.)_

**Comment by S4NSKAR** [comment]
A Lot thanks to you for creating this awesome project and keeping up the development with great support <3

> 1. One approach would be to use ffmpeg to create the preview clips but then this will only work for video wallpapers and then there is the added application size increase bundling ffmpeg (~60mb)

I am not so experienced player like you in coding, but if this can be added like a DLC (Downloadable Content) without hard-hitting and bugging the present code, then it could be an improvement. But it might not be worth the size and hard work put into it right now.

> 2. Another approach would be to skip the preview clips and thumbnail all together, but that will make the library ugly - one approach would be to create the thumbnail during wallpaper playback but unfortunately the code did not work for me #150

Can it be programmed simply to store the list of file in a queue and then simply automatically record the thumbnails and put into the library one by one as it does now (but without user interference to set desc, auth, etc.) ?...

> Lively ships its own custom web browser(based on chromium) and videoplayer (based on mpv player) which increases the size.
> Lively supports multiple wallpaper players (main app and wallpaper players are separate programs) and webview implementation is under work which has the potential to reduce appsize in the future.
> 
> At the core of it windows is doing all the work and that app is likely using windows media player which Lively also supports under videoplayer settings.
> Honestly if size is a concern and only video wallpapers are required then my software might not be best fit for you.
> You can try alternatives like:
> https://github.com/Francesco149/weebp

Thanks for that detailed information. I got the space (well, a lot), and this software suits my exact need. There are only 3 top Live Wallpapers software with high potential in my opinion: Lively Wallpaper, Wallpaper Engine, and [ScreenPlay live wallpaper](**https://gitlab.com/kelteseth/ScreenPlay**). Yours is the best in my need. Please keep continuing this great project.

> I don't really understand what you mean by collaboration, its a closed source software right?
> [Playlist](https://github.com/rocksdanister/lively/issues/137) is coming soon, unfortunately due to the complications that arise from many wallpaper types Lively supports and there only being one person working on this project - adding new features like this properly supporting everything takes time.
> _(I removed the link in original comment because their hosting stolen work with no credit.)_

Ok, I understand. Ignore that site and Sorry for linking a pirated kind of website.

**Comment by rocksdanister** [comment]
>Can it be programmed simply to store the list of file in a queue and then simply automatically record the thumbnails and put into the library one by one as it does now (but without user interference to set desc, auth, etc.) ?...

Only the preview window, will try 🤔

**Comment by rocksdanister** [comment]
with gif & thumbnail creation:

https://user-images.githubusercontent.com/17554161/114258664-c8c75800-99e5-11eb-81f9-15133d979b43.mp4

with only thumbnail creation:

https://user-images.githubusercontent.com/17554161/114259389-3629b780-99eb-11eb-82f5-2e04b8a7ee9f.mp4

**Comment by rocksdanister** [comment]
Final demo~

https://user-images.githubusercontent.com/17554161/114312231-9c0f5f80-9b0f-11eb-9d4a-773ce6326bec.mp4

**Comment by S4NSKAR** [comment]
Awesome!

BTW, can you share that Ghostrunner wallpaper...and from where did you get that?

**Comment by rocksdanister** [comment]
Its not a wallpaper.. just a gameplay recording I had lying around 😅

Final final demo:
https://www.youtube.com/watch?v=Nk6sF1r9J0U

Beta is out:
https://github.com/rocksdanister/lively-beta
