### ISSUE TITLE
Cef Plugin File Flagged as IDP.Generic Threat by Avast Premium Security

### ISSUE THREAD

**Issue by aacayaco** [rocksdanister/lively#299]
Process bug, if false positive, whole application will crash - automatically moved to virus chest/sandbox.

CefSharp.BrowserSubprocess.exe in "%\AppData\Local\Programs\Lively Wallpaper\plugins\cef" gets detected as IDP.Generic threat by Avast Premium Security with the most recent build: v1.1.9.0

Windows 10 Home 20H2
OS Build: 19042.789

Current Avast Premium Security build
![image](https://user-images.githubusercontent.com/3634801/107235329-8b833000-6a5f-11eb-99c1-402c064713ce.png)

**Comment by rocksdanister** [comment]
False positive, likely heuristic detection; It might be possible to submit it and get it removed but quite frankly I don't care because... most av programs are spyware themselves:
https://www.techdirt.com/articles/20191209/08120243531/avast-ceo-downplays-collection-400-million-users-browsing-data.shtml
https://gizmodo.com/stop-using-avast-and-avg-plugins-right-now-1840213548

I will only be looking at Windows defender status.
