### ISSUE TITLE
Wallpapers position aren't synchronized between displays

### ISSUE THREAD

**Issue by Syycorax** [rocksdanister/lively#309]
**Describe the bug**
Video wallpaper isn't sync between both screen

**To Reproduce**
1. Add a video wallpaper
2. Click on 'Duplicate Wallpaper'
3. Select the wallpaper

**Expected behavior**
The two screen should be playing the video simultaneously

**Desktop (please complete the following information):**
 - OS: Windows 10 pro 19041

**Additional info**
The settings (gamma, brightness etc) should also be synchronized if you chose 'Duplicate'

**Comment by rocksdanister** [comment]
>The two screen should be playing the video simultaneously

That will be difficult since the wallpapers plugins are separate programs (mpv player in this case for video wallpaper) and launching them simultaneously will be difficult.

What can be done is to reset the video position to beginning once all the wallpapers are loaded in duplicate mode.
Plan is to implement a Synchronise() / SetPosition() function in IWallpaper interface.

>The settings (gamma, brightness etc) should also be synchronized if you chose 'Duplicate'

Maybe later https://github.com/rocksdanister/lively/issues/264.. this is not so simple to do with the current LivelyProperties API setup without affecting existing users.

**Comment by rocksdanister** [comment]
@hooke007 What [message](https://github.com/mpv-player/mpv/blob/master/DOCS/man/ipc.rst) do I send to set media position during playback? `--start=<relative time>` is not working.
(I am guessing it only works before playback starts.)

**Comment by hooke007** [comment]
yes, `--start` just works once. I do not know how to handle it. Maybe create an new issue to mpv developers.

**Comment by rocksdanister** [comment]
Got it!
`{"command":["seek", "0", "absolute"]}`

**Comment by rocksdanister** [comment]
For default video player mpv and browser cef - gif/video/stream/webpage gets reloaded and sync in duplicate mode (There will be a few milliseconds difference.)
External program wallpapers unity games/applications don't sync.. don't think I can do much about that right now.

Issue regarding settings can be tracked separately https://github.com/rocksdanister/lively/issues/264
