### ISSUE TITLE
Can't play Steam games

### ISSUE THREAD

**Issue by dum4ik** [rocksdanister/lively#355]
When I open Steam game with different resolution than my PC (lower), it starts firstly, but after that I'm thrown out on the desktop. What should I do?

**Comment by rocksdanister** [comment]
Fill the issue template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
