### ISSUE TITLE
Error when selecting wallpaper

### ISSUE THREAD

**Issue by JoelTech43** [rocksdanister/lively#379]
Hi,
I really like Lively and have had it for ages but it kept saying that a new version was available so I uninstalled it and downloaded the new version.
However, on startup, whenever I clicked on a wallpaper to select it, it gave me an error message. Then I notice that, in the box where it shows you how many displays you have (control panel), It said I had 0 displays. This is weird as it had worked before but not now. I have put the log file below.
I hope you can help me as I love the wallpapers
Thanks,
Coding-Mole
[lively_log_20210321_210601.zip](https://github.com/rocksdanister/lively/files/6178411/lively_log_20210321_210601.zip)

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/377

> Then I notice that, in the box where it shows you how many displays you have (control panel), It said I had 0 displays.

Its a button that opens control panel and it shows the number of running wallpaper, not connected display.

**Comment by JoelTech43** [comment]
Thank you for telling me what that was for!
However, I still have the problem that when clicking on a wallpaper, it flashes up an error message.
The only exception to this is the Eternal light wallpaper which works fine but all the others do not and I cannot add my own!
I don't know whether this is something that I've done wrong or not but please could you help!
[lively_log_20210321_212846.zip](https://github.com/rocksdanister/lively/files/6178430/lively_log_20210321_212846.zip)

**Comment by JoelTech43** [comment]
Also, as it is marked as a duplicate of #377, which I agree with, I opened this as, although you asked them a few questions on this problem, you did no give an answer.
@

**Comment by rocksdanister** [comment]
Yes, because the web browser plugin got deleted by hyper aggressive av programs purely based on suspicion without even alerting the user... eternal light is a video and videoplayer plugin is fine.
I only test with windows defender, third party anti-virus programs are not considered.

One solution is to add exception to lively install folder but other users did not have any success with that approach.. other than to  remove the av program I don't have any solution at the moment.
