### ISSUE TITLE
Discord Server for Lively?

### ISSUE THREAD

**Issue by xFGhoul** [rocksdanister/lively#387]
**Is your feature request related to a problem? Please describe.**
it's not related to a problem.

**Describe the solution you'd like**
A simple Discord Server where others can share bug reports, chat, share wallpapers, and you as the creator, share new features(teasers?) or announcements etc.

**Describe alternatives you've considered**
Gitter? LOL but Discord may be the better choice

**Additional context**
None.

**Comment by Ucef27** [comment]
This would be awesome!

**Comment by xFGhoul** [comment]
@rocksdanister review?

**Comment by rocksdanister** [comment]
Lively had a discord server in the past, I deleted it due to personal reasons.

>A simple Discord Server where others can share bug reports, chat, share wallpapers, and you as the creator, share new features(teasers?) or announcements etc.

Honestly I much rather not have low quality bug reports, even in github many don't follow the issue template and it takes a lot of back and forth discussion to understand the problem.. moreover at the moment I am going to be the one diagnosing and fixing the bug so it just makes it more difficult if bug reports are spread across multiple places like that and impossible to keep track of.

[For example, there is over 600+ comments in one of the old discussion thread in Lively's subreddit.. all of which is hard to search.](https://www.reddit.com/r/LivelyWallpaper/comments/i4yfpi/7820_discussionhelp_megathread/)

Regarding wallpaper sharing currently you can post in reddit page, I also have plans to built in wallpaper library within the app itself.

Will consider creating a new server maybe in the future.

**Comment by clementwzk** [comment]
It would be amazing!

**Comment by rocksdanister** [comment]
https://discord.gg/fHfFgWntvm
