### ISSUE TITLE
"Something went wrong" Error

### ISSUE THREAD

**Issue by mckingwastaken** [rocksdanister/lively#391]
So basically, whenever i try to choose a wallpaper, an error pops up saying something along the lines of: "Oops! Something went wrong." and thats it. Restarting everything doesnt work. Please help!
[lively_log_20210325_205504.zip](https://github.com/rocksdanister/lively/files/6207200/lively_log_20210325_205504.zip)

**Comment by rocksdanister** [comment]
>Das System kann die angegebene Datei nicht finden.

Duplicate: https://github.com/rocksdanister/lively/issues/358

**Comment by edwinedj** [comment]
This problem was a headache for me...finally i found out the solution by downloading other wallpaper engine...it says mfplat.dll could not be found.....then i looked for yt videos and got the solution....open apps and feature - click optional features - click add a feature - install media feature pack.....and your done ! this steps worked for me....sry for any grammer mistakes :) reply if it workss

**Comment by edwinedj** [comment]
> > Das System kann die angegebene Datei nicht finden.
> 
> Duplicate: #358

checkkk
