### ISSUE TITLE
Lively wallpaper gives the sound, but not the wallpaper I selected.

### ISSUE THREAD

**Issue by MurrenMods** [rocksdanister/lively#394]
I hear the sound of my wallpaper, but I can only see the default wallpaper image. I saw another issue about this, but it was closed telling me it was solved, but i couldn't find a solution in the thread. Thanks in advance!

**Comment by rocksdanister** [comment]
Have you tried restarting windows?

**Comment by MurrenMods** [comment]
> Have you tried restarting windows?

Yup, just restarted my computer. Doesn't seem to help.

**Comment by rocksdanister** [comment]
**Fill the issue template:**
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by MurrenMods** [comment]
I just fixed it, appereantly it was clashing with Wallpaper Engine that ran in the background. I forced to close it with task manager and restarted my pc. It works now, but thanks for the help anyways!

**Comment by rocksdanister** [comment]
That's a weird combination.. using two wallpaper apps same time xD

**Comment by MurrenMods** [comment]
I used a crack of WE before but it worked terrible and lively is just superior in every way anyways so I switched. Being too lazy to uninstall is more of a point lmao
