### ISSUE TITLE
Wallpaper not working

### ISSUE THREAD

**Issue by snoowfall** [rocksdanister/lively#408]
I tried selecting a wallpaper but nothing happened. None of the wallpapers work, but Lively says that they are applied. Please help!!1

**Comment by rocksdanister** [comment]
**Fill the issue template:**

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by snoowfall** [comment]
Nevermind, for some reason my PC started blue screening a lot. The issue was my touchpad driver. I booted to safe mode and reinstalled the driver, and when I rebooted, Lively worked again. So, problem fixed. (still don't know how)
