### ISSUE TITLE
Wallpaper does not span to second monitor on boot

### ISSUE THREAD

**Issue by arborescere** [rocksdanister/lively#412]
When I start my machine up and log in the animated wallpaper is only present on my primary display. The secondary display is just black. If I go into the multi-monitor settings and toggle between any other setting and span, the wallpaper returns to the intended behavior.

**Comment by rocksdanister** [comment]
**Fill the issue template:**

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by arborescere** [comment]
Apologies, here you go:

To Reproduce:
Click monitor icon next to min/max/close buttons at top of window
Set an animated wallpaper to "span across screens"
Reboot
Wallpaper is only on primary monitor, with black static background on secondary monitor. In settings, "span across screens" is still selected.

Expected behavior:
Monitor should span across screens after reboot.

Desktop:
OS: Windows 10 Pro 1909
Wallpaper: Ribbon

Log file (Important)
[lively_log_20210330_195313.zip](https://github.com/rocksdanister/lively/files/6233504/lively_log_20210330_195313.zip)

**Comment by rocksdanister** [comment]
in Ribbon project's `js/script.js` file, is the following function present at the bottom:
```js
window.onresize=()=>{
    location.reload();
}
```

**Comment by arborescere** [comment]
No, it looks like there is no reference to window.onresize anywhere in the file.
Also sorry again, I forgot to mention I'm using the Windows Store version.

**Comment by rocksdanister** [comment]
>The secondary display is just black. 

This basically means Lively did its job and the web browser window did span across all displays.. 
But the wallpaper itself did not update because it is not coded to handle [resize](https://www.w3schools.com/jsref/event_onresize.asp), adding the code should fix it:
```js
window.onresize=()=>{
    location.reload();
}
```
Its not pretty reloading every time window size change, but for simple webpages this should be enough.
