### ISSUE TITLE
Cant set wallpaper

### ISSUE THREAD

**Issue by FILIPpro40** [rocksdanister/lively#434]
Today i when i turn on my computer, i go into lively and when i tried to sett wallpaper i get error. I didn't have this problem before and everything was working perfect.

**Comment by rocksdanister** [comment]
The issue template exists for a reason.. error can mean any number of things.
I'm just going on a guess and marking it as duplicate https://github.com/rocksdanister/lively/issues/358

**Comment by FILIPpro40** [comment]
Still got this error. Sadge.

**Comment by rocksdanister** [comment]
**Fill the issue template:**
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by FILIPpro40** [comment]
lively_log_20210406_164639

**Comment by rocksdanister** [comment]
Something went wrong, I can only see the filename and not the file itself.

Can you try the latest beta build:
https://github.com/rocksdanister/lively-beta/releases
