### ISSUE TITLE
Keyboard shortcut breaks the application (Win + Tabs)

### ISSUE THREAD

**Issue by ungc1atwit** [rocksdanister/lively#438]
Hi the app works fine, there is one issue that I faced. I usually use Win + Tabs to change my applications or new desktop and whenever I do that the wallpaper just disappear, I have to quit the app and reopen and it works. Am I the only one having this issue?

**Comment by rocksdanister** [comment]
I can't reproduce this issue on my system..

Also fill the issue template properly:
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by ungc1atwit** [comment]
Sorry, I just write the comment quickly after figuring the issue. Below is the detailed information.

**Describe the bug**
There is a keyboard shortcut (Win + Tab) to change to the new desktop or the other applications. Whenever I click on shortcut, I can still see the wallpaper. However, when I stop the behavior, the wallpaper just disappear while lively app is still on. 

**To Reproduce**
Steps to reproduce the behavior:

1. Click on windows keyboard shortcut (Win + tab) - the wallpaper still works
2. Then close it by clicking on "Esc" or clicking the shortcut again
3. The live wallpaper just disappeared while the app is still working
4. To re-run the app, I need to quit the app and open it again

**Expected behavior**
I expect that wallpapers still work whenever I use this shortcut. It worked when I use shortcut (Alt + tab), which is also used for changing to the other applications, not desktop. 

**Screenshots/Video**

https://user-images.githubusercontent.com/65377130/113813803-921be400-973e-11eb-9bd5-8c10258aa02a.mp4


**Desktop (please complete the following information):**

OS: Microsoft Windows 10 Enterprise Insider Preview 10.0.21343
CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
GPU: Intel(R) UHD Graphics 630
GPU: NVIDIA GeForce GTX 1070 with Max-Q Design

**Log file (Important)**
[lively_log_20210407_011716.zip](https://github.com/rocksdanister/lively/files/6269156/lively_log_20210407_011716.zip)

**Comment by rocksdanister** [comment]
I managed to recreate the error on my system, but it happens at random.. looking at the log:
`2021-04-07 01:00:04.2438|ERROR|livelywpf.NLogger|failed to set parent, HRESULT:1400`
Looks like explorer/shell restarted.. not sure if Lively is causing this or is it only a problem when taskview/timeline is enabled.

I recently added code to recover from such cases https://github.com/rocksdanister/lively/commit/f15e4265cd60ac30f92564d27d83ef74514fde37 and sure enough testing with the latest beta build I got the `WM_TASKBARCREATED` - new taskbar created message (explorer restart) and Lively recovered.

Can you try the latest beta build:
https://github.com/rocksdanister/lively-beta/releases
(I recommend uninstalling windows store version of Lively to avoid confusion)
and see if it recover, share the new logfile.
