### ISSUE TITLE
Wallpaper ribbon stops changing color

### ISSUE THREAD

**Issue by SanTi-04-bit** [rocksdanister/lively#444]
Hi. My wallpaper stops changing color after a certain time and it just starts to work again when I open the Lively App and chose a random wallpaper. After switching back to the wallpaper that I want it starts without any problem for a specific duration and then stops again. It would be great if you could fix this bug, please.

https://user-images.githubusercontent.com/81932195/114021881-15d1ef80-9869-11eb-9db2-bec7e23f8d23.mp4

**Comment by rocksdanister** [comment]
Wallpapers and Lively are [separate](https://github.com/rocksdanister/lively/wiki), this repository is mostly focused on software side and not the wallpaper... the wallpapers included are mostly just examples.

To be precise this is not a software bug but rather an issue with the code of Ribbon (it is a webpage) and will require changes to be made to the javascript code of the webpage itself.. I will see what I can do when I get free time - but keep in mind I wont be able to push these changes to the actual Ribbon wallpaper from my end for existing users because of the reason I mentioned above.

**Comment by SanTi-04-bit** [comment]
Ok thank you for answering. But is there any way that it could be fixed
in the future? Have a nice day.

Am Do., 8. Apr. 2021 um 13:03 Uhr schrieb Dani John <
***@***.***>:

**Comment by rocksdanister** [comment]
Right click the wallpaper in library -> Open file location
This will open the folder with the source files, someone will have to look at the javascript code and write a fix.

**Comment by SanTi-04-bit** [comment]
Thank you!

Dani John ***@***.***> schrieb am Do., 8/04/2021 um 13:45:
