### ISSUE TITLE
Unable to add a Video Wallpaper

### ISSUE THREAD

**Issue by jauraphagwara** [rocksdanister/lively#467]
I downloaded a video wallpaper and tried to add it to lively but got this error.

Can you help me out with it?
![image](https://user-images.githubusercontent.com/82264845/116508913-f7976680-a8df-11eb-8dad-3fb8bd428019.png)

[20210427_021541.txt](https://github.com/rocksdanister/lively/files/6396614/20210427_021541.txt)

I have attached the log file and the screenshot of the error

**Comment by rocksdanister** [comment]
Why did you remove the system information from the logfile?
Follow the full template and attach the correct log zip file without any modification:
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File

**Comment by jauraphagwara** [comment]
[lively_log_20210429_115534.zip](https://github.com/rocksdanister/lively/files/6396702/lively_log_20210429_115534.zip)

https://user-images.githubusercontent.com/82264845/116510953-5f02e580-a8e3-11eb-9467-ef01f63c8976.mp4

I am on Windows 10 Pro 21H1 (Build : 19.43.962)

I have attached the screen recording and the zipped log file. Please let me know if you need anything else.

Thank You So Much !

**Comment by rocksdanister** [comment]
Somethings causing mpv player to crash.. probably some hardware/software compatibility issue.
Try the alternative vlc video player:
https://youtu.be/8vgrsoBGoHI?t=88
(early, untested.)
