### ISSUE TITLE
Program crash

### ISSUE THREAD

**Issue by madarauchiha1738** [rocksdanister/lively#493]
when i try to add a new wallpaper or really try to do anything to them it just crashes and if you could please get back to me thx

p.s keep up the good word

**Comment by dabjulmaros** [comment]
The dev will need a little more info to be able to diagonose this issue.
Please follow the issue templete.
Im guessing the logs will be helpful on diagnosing this issue ( please read the end of this comment for how to get the logs files)

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
