### ISSUE TITLE
Wallpaper not applying after updating to v1.5 

### ISSUE THREAD

**Issue by themrstone24** [rocksdanister/lively#498]
hey, 

Since the last update (few days before 17th may) the wallpaper don't apply. I only see my windows wallpaper and there is no error at all.
I can add new wallpaper like I usually do, I can click on them to apply but don't.
It's seems to process something somehow on the background but, you guess it, no wallpaper.
I tried to uninstall/install already but it did nothing.
The weird thing is it worked quite well before except that it took some time to setup the wallpaper after reboot and do weird things with the windows wallpaper (during the load process).

In any case that a good software very easy to use and polyvalent.

**Comment by rocksdanister** [comment]
Fill the issue template:
Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior
A clear and concise description of what you expected to happen.

Screenshots/Video
If applicable, add screenshots/video to help explain your problem.

Desktop (please complete the following information):

OS: [e.g. Windows 10 1909]
Which wallpaper was running at the time if any.
Additional context
Add any other context about the problem here.

Log file (Important)
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or
Navigate to Appdata folder C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs

**Comment by lordadrian112** [comment]
Im having the same issue too. ive downloaded and installed everything that came with the setup. i can  see the wallpapers but it doesnt apply when i select it.

**Comment by lordadrian112** [comment]
[lively_log_20210518_174031.zip](https://github.com/rocksdanister/lively/files/6498658/lively_log_20210518_174031.zip)

**Comment by rocksdanister** [comment]
Again.. follow the issue template, don't just dump the logfile.

**Comment by lordadrian112** [comment]
It's fine. It's working. Restarted my computer.

**Comment by themrstone24** [comment]
Ok so, Hey again,

Sorry for the issue template, my bad.
But today morning when I tried to load an custom/added wallpaper I've got this:
![bugLively](https://user-images.githubusercontent.com/32277189/118692861-cb01ab00-b80a-11eb-8ad8-69f03f17bcde.png)

When I got back to home and plug my laptop lively wake up and applied à random wallpaper and now it's working.
I don't know what to say/think, I didn't do anything but it work now for no reason.
So I will close this bug report.
Again awesome work and here the logs files:
[20210517_225344.txt](https://github.com/rocksdanister/lively/files/6503038/20210517_225344.txt)
[20210518_094958.txt](https://github.com/rocksdanister/lively/files/6503039/20210518_094958.txt)
[20210517_225212.txt](https://github.com/rocksdanister/lively/files/6503040/20210517_225212.txt)
