### ISSUE TITLE
Wallpaper launching fullscreen

### ISSUE THREAD

**Issue by ILikeLight** [rocksdanister/lively#508]

**Comment by ILikeLight** [comment]
Like the hole entire start is gone
its like the walpaper is over the actual desktop

**Comment by rocksdanister** [comment]
Try restarting windows.
If it still causes issue then fill the issue template:
**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`
