### ISSUE TITLE
The wallpaper disappears after I restart my computer and the old wallpaper from Windows comes back

### ISSUE THREAD

**Issue by rakanhumidan** [rocksdanister/lively#526]

**Comment by rocksdanister** [comment]
**Before proceeding**
Check the Wiki:
https://github.com/rocksdanister/lively/wiki/Common-Problems
and Issues:
https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue
to see if your problem is already addressed.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by rakanhumidan** [comment]
it worked the first day then its not working  and not giving me any error code

**Comment by rocksdanister** [comment]
Sorry I can't help you if you don't follow instructions.
