### ISSUE TITLE
Uninstalled but lockscreen wallpaper did not revert

### ISSUE THREAD

**Issue by derpalot** [rocksdanister/lively#611]
OS: Windows 10 Education

I uninstalled lively because I figured it was not for me however, whenever I turn on or restart my desktop the lock screen is set the wallpaper of the wallpaper set with lively and not my current wallpaper. 

I cannot also remove the "Some of these settings are hidden or managed by your organization" from both the lock screen and startup setting from the windows settings. It was not there before I installed lively and I've gone through the steps to regedit to turn off anything but nothing was turned on.

I am also running a ryzen 5 3600 gpu and amd 6700xt reference model if that matters.

**Comment by rocksdanister** [comment]
> "Some of these settings are hidden or managed by your organization"

Lively should not cause this.. I am not editing registry or anything, just using api provided by Windows to change lockscreen:
https://docs.microsoft.com/en-us/uwp/api/windows.system.userprofile.userprofilepersonalizationsettings.trysetlockscreenimageasync?view=winrt-20348

Could be a Windows education restrictions with group policy editor.

>I uninstalled lively because I figured it was not for me however, whenever I turn on or restart my desktop the lock screen is set the wallpaper of the wallpaper set with lively and not my current wallpaper.

Just change the lockscreen image again and restart, lockscreen image set won't change just because you uninstall Lively since it has nothing to do with Lively directly and handled by windows.

Related: https://github.com/rocksdanister/lively/issues/537
