### ISSUE TITLE
v1.7.0.2 Update lead to video wallpapers not working

### ISSUE THREAD

**Issue by powderblue042** [rocksdanister/lively#613]
Hi,
After I updated the program the video wallpapers I made aren't working anymore. :(
I love your program, help!
Thanks.

**Comment by rocksdanister** [comment]
Fill the issue template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by powderblue042** [comment]
Hi!

Video wallpapers don't work after update.

Upon opening download and install update, go to previously existing video wallpaper uploaded onto program. Error message "Oops... Looks like something went wrong :( In order to better understand this error and fix the issue, share the log file with the developer. Instructions....."

Expected video wallpaper to appear and play

No screenshots

Windows 10 laptop, ripples wallpaper planning at the time.

[lively_log_20210712_194232.zip](https://github.com/rocksdanister/lively/files/6803682/lively_log_20210712_194232.zip)

**Comment by rocksdanister** [comment]
Which version of Lively did you upgrade from?
