### ISSUE TITLE
Stream metadata fetch not working 

### ISSUE THREAD

**Issue by tellmewhy12** [rocksdanister/lively#631]
**Describe the bug**
When adding a youtube video the metadata & description don't get fetched automatically

**To Reproduce**
Drag in a Youtube video and look at Title saying "watch" and empty desciription

**Expected behavior**
The title and description getting fetched from youtube

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/71931749/126161866-961be8a8-c916-4b3f-a807-ba590e6a6ac6.png)

**Desktop (please complete the following information):**
 - OS: ![image](https://user-images.githubusercontent.com/71931749/126161890-e4cdccda-1d24-45c2-9448-e56cd97f4517.png)

**Log file (Important)**
[20210719_100122.txt](https://github.com/rocksdanister/lively/files/6840956/20210719_100122.txt)

**Comment by rocksdanister** [comment]
Windows store version of Lively is several versions old ( v1.5.0.2) due to https://github.com/rocksdanister/lively/issues/540 and lacks many features and bugfixes.

Latest installer version is v1.7.0.2

Further read:
https://github.com/rocksdanister/lively/wiki/Differences-Between-Distributions

Full changelogs:
https://github.com/rocksdanister/lively/releases
