### ISSUE TITLE
Lively starts with windows but wallpaper not restoring

### ISSUE THREAD

**Issue by AzazelHD** [rocksdanister/lively#640]
Hello guys, I don't know if this is intended or not, but even if the box "start on windows" is marked, app isn't displaying a background. It only just starts.

Is there anyway to start it with a selected background? If not, could you add this feature?

**Comment by rocksdanister** [comment]
Going to assume you are using windows store version of Lively (the issue template was ignored.. )
Its a display port/monitor issue, I did do a workaround but the store version is several months old due to bug https://github.com/rocksdanister/lively/issues/540#issuecomment-861459152

The installer version of Lively has the fix and should work as expected.

https://github.com/rocksdanister/lively/wiki/Differences-Between-Distributions
