### ISSUE TITLE
Wallpapers frozen / cant open web wallpapers

### ISSUE THREAD

**Issue by Fennecai** [rocksdanister/lively#641]
**Describe the bug**
no matter what type of wallpaper I try to use (including videos, HTML, webview, etc.) they all remain perfectly frozen. With videos, I can still hear the audio, but the image remains still.

additionally, I cannot open HTML or other web-based wallpapers half the time.

**To Reproduce**
1. click on wallpapers
2. see error box or frozen picture on desktop

**Expected behavior**
I expected the software to work like it has always done, I don't know why it stopped working correctly out of nowhere.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/10889213/127078853-d32252c7-2731-46d1-b336-6b574c4e4eae.png)
(this error only happens with web views and HTML videos, all other videos go error-free but remain frozen.)

**Desktop (please complete the following information):**
 - OS: windows 10
 - this happens with all wallpapers, it doesn't matter which one you pick.

**Additional context**
i have tried rebooting, re-installing, forcing the program closed in task manager then opening it again, pausing/unpausing the wallpaper, switching video players and web browsers in settings... nothing works.

**Log file (Important)**
[lively_log_20210726_190307.zip](https://github.com/rocksdanister/lively/files/6881961/lively_log_20210726_190307.zip)

**Comment by rocksdanister** [comment]
I see this previous issue from you https://github.com/rocksdanister/lively/issues/210
When/which version of Lively exactly did this new problem started happening? 
this sounds like issue is being caused by something else.

also Edge browser plugin requires [separate installation.](https://github.com/rocksdanister/lively/wiki/Web-Guide-I-:-Cef#webview2-microsoft-edge)
