### ISSUE TITLE
AfterBurner thinks it is a game

### ISSUE THREAD

**Issue by AzazelHD** [rocksdanister/lively#651]
Hey! 

Currently using last version for windows 10.

When having afterburner on (rivaturner statistics), the typical software to display fps cpu usage, gpu usage and temperatures etc, lively detects it as a game and info is displayed on the desktop too.

I think this is not intended but would be there a way to fix it?

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Common-Problems#lively-keeps-crashing-on-start
Reduce detection to low or add exception to the Lively processes in the rivatuner statistics app settings.

**Comment by AzazelHD** [comment]
Hi, i dont know why would this be a duplicate, i didn't find any topic. But it seems reducing detection level / adding an exception still doesnt fix it

**Comment by rocksdanister** [comment]
>Hi, i dont know why would this be a duplicate,  i didn't find any topic.

Because its been documented in the FAQ/wiki.

>But it seems reducing detection level / adding an exception still doesnt fix it

Setting detection to low worked for me in the past, for exception you will have to add all of the following programs:

- `<install_location>/livelywpf.exe`
- `<install_location>/plugins/cef/LivelyCefSharp.exe`
- `<install_location>/plugins/mpv/mpv.exe`

This is also not a direct issue of Lively, my help will be limited.
