### ISSUE TITLE
Lively keeps forgetting settings? / Shows the set-up guide on startup

### ISSUE THREAD

**Issue by HaZe5657** [rocksdanister/lively#656]
Ok so it seems to show the set-up guide in 1/3 boots, This is a bit annoying, I wonder if this is an issue other have too and I hope this will get fixed later on.

**Comment by rocksdanister** [comment]
First time hearing about this.. its a bug.

Fill the issue template so that the issue can be looked into:
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
