### ISSUE TITLE
Automatically create an mpv.conf file so that the system does not use the user's own mpv.conf file

### ISSUE THREAD

**Issue by DeltaForCain** [rocksdanister/lively#670]
When using mpv already, most users will have an mpv.conf (likely in %appdata%/mpv/), that gets read first. 
If that mpv.conf has somewhat niche options, the Lively mpv option will show a blue screen instead of the video file. I believe the culprit option to be running Vulkan as the video renderer.

Putting a default, minimal config into the folder mentioned [here](https://github.com/rocksdanister/lively/wiki/Video-Guide#mpv) solves this issue neatly without interfering with the user's regular mpv install.

As such, I believe an mpv.conf with minimal options (I use profile=gpu-hq and hwdec=auto only) should be created automatically on install (if there is not yet one at that location already) to avoid running into this issue at all.

**Comment by rocksdanister** [comment]
>As such, I believe an mpv.conf with minimal options (I use profile=gpu-hq and hwdec=auto only) should be created automatically on install (if there is not yet one at that location already) to avoid running into this issue at all.

No, I would prefer the config be handled by Lively itself:
https://github.com/rocksdanister/lively/blob/cab6e864108ac20cc910c5bb58accaa4d09c5f15/src/livelywpf/livelywpf/Core/Wallpapers/VideoMpvPlayer.cs#L103-L148
or `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\mpv\mpv.conf` file if present.

Creating auto-file may conflict with some of the Lively settings in the future due to human error etc..

https://mpv.io/manual/stable/#legacy-auto-profiles
> Depending on what you do, passing --no-config or --config-dir may be a good idea to avoid conflicts with the normal mpv user configuration intended for CLI playback.

I think this approach would be better.

**Comment by DeltaForCain** [comment]
Passing --no-config might also work I presume, or specifying the folder where to look for the config. 

Good idea and thank you for the quick response!

**Comment by rocksdanister** [comment]
patched:
https://github.com/rocksdanister/lively-beta/releases
