### ISSUE TITLE
Lockscreen background seems to be random when same picture is used for login screen

### ISSUE THREAD

**Issue by Baumgaer** [rocksdanister/lively#678]
**Describe the bug**
In windows 10 you can check the option "show lock screen background picture on the sign-in screen" (most bottom checkbox in lockscreen options). When this Checkbox is activated it seems that any picture, which was used before, is taken as a background but not that one which is used by lively.

**To Reproduce**
1. go to Settings > Personalization > Lock Screen
2. scroll down
3. check "show lock screen background picture on the sign-in screen"
4. in lively go to system
5. check lock screen picture
6. press windows + l (Lock shortcut)

Now you have any picture but not the expected one

**Expected behavior**
A snapshot of the current live wallpaper should be taken and the lively setting should not be applyed when the corresponding option in lively is disabled.

**Screenshots/Video**

https://user-images.githubusercontent.com/33933602/130222849-72ca560d-2556-488a-b1b9-2fa85f75ffcf.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
- A youtube video was loaded as background, but happens with any other lively wallpaper

**Additional context**
I already tried to use other players, but it's always the same

**Log file (Important)**
[lively_log_20210820_122148.zip](https://github.com/rocksdanister/lively/files/7020908/lively_log_20210820_122148.zip)

**Comment by rocksdanister** [comment]
>check "show lock screen background picture on the sign-in screen"

The desktop/lockscreen image is set only during live wallpaper is set.. toggling the setting won't have a direct effect if live wallpaper is already set.
Easiest solution would be to just restart the wallpaper I guess.

There are also some bugs with lockscreen picture https://github.com/rocksdanister/lively/issues/537 
I'm thinking of disabling it till its resolved.

> lively setting should not be applyed when the corresponding option in lively is disabled.

I get what you mean but part of the reason I put that setting under "System" is because it does make some changes to system (and yes the screensaver settings need to be moved from ther.. that was a rushed decision.)
For example you set a system wallpaper through Lively, then close the app.. next time you open the app how do I determine the current wallpaper is set by the user or Lively.

>I already tried to use other players, but it's always the same

Only mpv player is bundled with Lively, rest other than wmf require optional download (if plugin not found then settings will revert to mpv.).. also the image capture feature is currently only implemented for mpv, CefSharp and Edge.
