### ISSUE TITLE
Switch youtube-dl to yt-dlp because youtube-dl is likely never going to be continued.

### ISSUE THREAD

**Issue by Ixyk-Wolf** [rocksdanister/lively#729]
Well, this could be an issue in the future because youtube-dl isn't likely to be continued and it could provide issues with newer videos.

It would be easy to switch to [yt-dlp](https://github.com/yt-dlp/yt-dlp)

I use MPV for my wallpapers, I'm not sure exactly how it works with other media players though.

**Comment by rocksdanister** [comment]
I did notice youtube-dl is not being updated these days..
Honestly I am thinking of not bundling streaming plugin (youtube-dl) by default.. this is creating issue like bandwidth usage, wallpaper not restoring when starting up windows if internet not available because modem has not finished booting up etc.

The original intention of this feature was for livestreams of space.. but its being used by many for simple videos.

**Comment by Ixyk-Wolf** [comment]
I would give a warning when using web streams as wallpapers just so that the user knows.

**Comment by rocksdanister** [comment]
I doubt it makes a difference, mpv is only using yt-dl for getting the link and handling everything else by itself.
