### ISSUE TITLE
Hi, I add website as wallpaper, but get nothing

### ISSUE THREAD

**Issue by Leroy-X** [rocksdanister/lively#758]
https://synesthesia.rikard.io/

I want add this site as wallpaper, but empty, who can help me.

**Comment by rocksdanister** [comment]
Fill the issue template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by Leroy-X** [comment]
@rocksdanister Hi,it's works now. excuse me, does Lively support the interaction of keyboard input, or how to enable the keyboard to interact with the webpage, sorry, my English is not good, thanks to Google Translate

**Comment by rocksdanister** [comment]
![Screenshot 2021-09-27 085459](https://user-images.githubusercontent.com/17554161/134841101-d05f2e5e-3289-4d56-b527-3a21527f8f89.png)

**Comment by Leroy-X** [comment]
Thanks so much: )
