### ISSUE TITLE
Delay when using desktop peek

### ISSUE THREAD

**Issue by tianshiyan1314** [rocksdanister/lively#786]
There is a slight delay when the mouse is placed in the lower right corner of the desktop to display the desktop

**Comment by rocksdanister** [comment]
1. Can you share a video of this happening?
2. What's your gpu, cpu name?

**Comment by GhazanfarAteeb** [comment]
I guess it's not an issue because I also faced it but it seems like it is opening late on start up when we restart the system I confirmed my system by restarting it 2 to 3 times whether how faster it will apply after restarting though first time no wallpaper 2nd time and so on delayed wallpaper. Well for my system I have Intel core i7 10510U and dedicated 2 GB NVIDIA Geforce MX130 GPU
