### ISSUE TITLE
When switching applications, Lively starts the wallapaper

### ISSUE THREAD

**Issue by Kim2091** [rocksdanister/lively#789]
**Describe the bug**
When I switch between applications (both are Fullscreen, but I have Lively set to pause on foreground anyway), Lively begins playing the wallpaper again. This is visible both through the taskbar and by monitoring GPU usage.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
- Custom ShaderToy Wallpaper: https://www.shadertoy.com/view/XlfGRj

**Additional context**
I use StartIsBack alongside Lively, but I can't verify that's the issue.

**Log file (Important)**
https://controlc.com/39b0aaa6

**Comment by rocksdanister** [comment]
It may play the wallpaper momentarily when the foreground window change (taskbar, app-switcher etc..) 
https://github.com/rocksdanister/lively/wiki/Performance#foreground-process
But it should immediately pause as you change focus back to application if foreground pause is enabled.

>I use StartIsBack alongside Lively, but I can't verify that's the issue.

This maybe the cause.. I have some exceptions set for some default windows elements and apps to **always** play:
https://github.com/rocksdanister/lively/blob/4b73808d01480d8d3a9414619289b3ceb6b90ba4/src/livelywpf/livelywpf/Core/Playback/Playback.cs#L22-L39

Can you verify this by temporarily turning it off?

**Comment by Kim2091** [comment]
I was able to disable StartIsBack for my user profile, and the issue sadly persists.

I think I've narrowed it down though. It seems to only be when Discord is selected. It seems to happen both with and without BetterDiscord enabled. When switching between applications other than Discord, the wallpaper is temporarily enabled as you mentioned, but nearly immediately disables itself again.

**Comment by rocksdanister** [comment]
Lively has a default application playback rule set for Discord:
![Screenshot 2021-10-12 073219](https://user-images.githubusercontent.com/17554161/136878507-24d4c25c-8320-4f1a-88b1-7089f14fa3af.png)

This is workaround because the way discord handles minimizing to tray and then restoring is weird (`ITaskList_Hidden` window property is used).. the changes to its state don't update properly when checking so I have no way to know if its hidden.

As long as that rule is set, wallpaper will continue to run if discord is foreground and it should pause when you switch to another app.

**Comment by RedSnt** [comment]
I guess I should install the Github version, because the Windows Store (WS) version doesn't have Discord as a default application. And Now that I've set up Discord.exe and Update.exe in the WS version it doesn't seem to do pause the animation when Discord is in the foreground 😔

**Comment by rocksdanister** [comment]
Its because the UI changed, new UI just shows apps that have Pause rule only.. you can still edit it:
Navigate to 
`%LocalAppData%\Packages\12030rocksdanister.LivelyWallpaper_97hta09mmv6hy\LocalCache\Local\Lively Wallpaper` 
or for installer
`C:\Users\<UserName>\AppData\Local\Lively Wallpaper\AppRules.json`

Edit `AppRules.json` and restart Lively to apply new setting.
