### ISSUE TITLE
Don't use user Documents folder (OneDrive sync)

### ISSUE THREAD

**Issue by Martin5001** [rocksdanister/lively#86]
Your app is really great. I have just a little suggestion:

I use OneDrive to automatically sync my files across devices. And I noticed Lively saves some files in user Documents folder, which then gets automatically uploaded to OneDrive too. But as these Lively files are not documents or photos, I don't want them to be in my OneDrive. Would it be possible to use different folder than user Documents for the Lively data? (Maybe this could be optional in case someone would want Lively to be in Documents, but I believe most people wouldn't.)

Thank you

**Comment by rocksdanister** [comment]
Currently portable build keeps everything inside its folder.
As to why I'm writing to outside of lively folder, this was my original [answer:](https://www.reddit.com/r/LivelyWallpaper/comments/gco5e0/3520_weekly_discussionhelp_megathread/fpjcfvy?utm_source=share&utm_medium=web2x)

> 
> Lively is not installed in documents folder; plugins(web browser, videoplayer etc) and wallpapers used by lively are only installed there..
> 
> This is done for various reasons:
> 
> Without admin rights software are not allowed to write to C:/Program Files installation location; writing there is not good practice either. Lively needs to write files when installing wallpapers.
> 
> Ease of access, easier to manage for the end user.. as oppose to telling users to goto %AppData% etc
> 
> This approach is very similar to other popular programs such as rainmeter
> 
> Alternatively lively portable build is self contained, everything is inside lively folder.
> 
> 
> 
> Q. And once i have dragged and dropped a ZIP file into the Lively window, can i move the ZIP file some where else from where i dragged it? Does it copy the ZIP into Lively, or does it does Lively link to the folder from where it was dragged?
> 
> Lively .zip are always installed/extracted in Documents/Lively Wallpaper/wallpapers folder or Parent directory if portable build of lively.
> 
> Yes you can delete the zip file, you can also create a new Lively .zip file by right clicking the wallpaper in Library and selecting "Create Lively .zip"
> 
> Only exception is when you drag and drop non .zip files, Lively is only storing its location information and not copying it to wallpaper folder..you will see a square disk icon topright on the wallpaper tile in Library in this case; you can also create "Lively .zip" files for these wallpapers if you want to keep a copy/need to install it.


I do plan to change the few things with v1.0, lively browser will be in programfiles and dropping support for plugins like mpv player and tempfiles will be in appdata.

As for selectable lively wallpaper install folder, there are a few challenges:
1. If I let user select this during installation, then I will have to let lively know where this location is since the installer script (inno) and lively are separate things.
2. If I let users change the folder in lively settings,  again I will have to let the Inno uninstaller know so that It can prompt user weather to delete the folder after uninstall or I decide to add new wallpapers in an update and the installer needs to know where to extract it.

Will have to look into an optimal way of doing this, adding it in registry might be an option/ or some creating xml file by innoscript are options to look into.

**Comment by etjrowe** [comment]
Came to report the same issue with OneDrive. Will switch to portable for now. Looking forward to v1.0!

**Comment by rocksdanister** [comment]
Done!
![Annotation 2020-08-01 101616](https://user-images.githubusercontent.com/17554161/89094376-d8b38480-d3e0-11ea-96e0-b651311c7085.jpg)
