### ISSUE TITLE
Too many console.log() calls make the wallpaper unresponsive

### ISSUE THREAD

**Issue by paulmiro** [rocksdanister/lively#904]
**Describe the bug**
Using too many JavaScript console.log() calls in a web wallpaper cause the wallpaper to no longer react to any user input.
Other functions of the wallpaper may still work though, meaning the wallpaper doesn't just crash completely.

**To Reproduce**
Download and open [console test.zip](https://github.com/rocksdanister/lively/files/7585064/console.test.zip) in Lively.
The box periodically switches color between red and green. it also changes to blue on mouseover.
Once you press the button, it spits out 100 console.log() messages. (it sometimes takes multiple clicks to break)
After this, the box still changes between red and green, but it no longer switches to blue on hover.
This seems to happen with any JavaScript file that spits out a certain number (47 for me) of log messages.

**Expected behavior**
Pressing the button should have no effect, as it only spits out console.log() messages.

**Desktop (please complete the following information):**
- OS: Windows 10 2004 (Build 19041.1348)
- Wallpaper: Any web wallpaper that uses console.log() a lot

**Additional context**
Turning Debug on or off under Settings -> Misc seems to have no effect.
You don't want to know how long it took me to find out that out of all the possible things, THIS was what caused issues with my stuff xD

**Log file (Important)**
[lively_log_20211123_005826.zip](https://github.com/rocksdanister/lively/files/7585111/lively_log_20211123_005826.zip)

**Comment by wanickols** [comment]
Wow thank you so much! Wanted to thank you and add to possible errors people may be experiencing because of this.  I was having an assortment of random issues, including my click interaction failing. I also experienced an assortment of odd unique bugs such as my lively settings being ignored (playing while Fullscreen and focused), various issues upon restarting my computer and even crashes from restarting windows multiple times. After removing my console logs I had been using to check values in creation, all of these issues ceased. Not a huge bug, but an irritating one as I am sure you know.

**Comment by rocksdanister** [comment]
@amaitland any idea what's the cause?

I'm just using [`chromeBrowser.ConsoleMessage` ](https://github.com/rocksdanister/lively-cef/blob/0d67ad422686e352fc8004e353c6cd59def05e57/src/LivelyCefSharp/Form1.cs#L505-L512) .. even commenting out `WriteToParent` is not helping.

**Comment by amaitland** [comment]
Are there any errors in the cef log file?

**Comment by rocksdanister** [comment]
Nothing unusual in the log:
[logfile.txt](https://github.com/rocksdanister/lively/files/7739187/logfile.txt)

**Comment by amaitland** [comment]
If you load the same webpage in the minimum example do you see the same behaviour? 

https://github.com/cefsharp/CefSharp.MinimalExample
