### ISSUE TITLE
Some local wallpapers not working with webview browser and stream wallpaper issue

### ISSUE THREAD

**Issue by Novo** [rocksdanister/lively#913]
First of all, I want to thank you for this nice piece of Software!
For me, the last "good" Version is 1.7.2.6, here's why:

Rain v2 Theme does only work with WebBrowser Engine CEFSharp,
but Youtube Stream only works when switching to MS Edge engine.

Youtube Stream says, it cannot play on this Browser.
Adding updated youtube.dl.exe or EdgeWebView2RuntimeInstallerX64 as mentioned in your readmes have no effect.
I'm using Windows 11.

**Comment by rocksdanister** [comment]
>Rain v2 Theme does only work with WebBrowser Engine CEFSharp,

Edge Webview cannot handle local files due to CORS issue which Microsoft will need to add special support for.

>Youtube Stream says, it cannot play on this Browser.

I am opening yt links in embed browser now since yt-dl plugin is no longer being maintained.

>Adding updated youtube.dl.exe or EdgeWebView2RuntimeInstallerX64 as mentioned in your readmes have no effect.

The file name and location need to be correct: `youtube-dl.exe` https://github.com/rocksdanister/lively/issues/837#issuecomment-949892382

Both of these are not the result of rewrite.

**Comment by Novo** [comment]
All I can say that the last Version before rewrite works with the Rain v2 theme and does not have issues playing YT streams.
The newest release has either problems with the streams (CEF engine) OR does not play Rain V2 theme (edge engine).
When changing Wallpaper from stream to Rain V2 or wise versa, I have to change the Wallpaper engine, too.
If you say this is not a bug but a feature by design, close this.
I just wanted a solution for that.

thanks and have a nice day.

**Comment by rocksdanister** [comment]
Please read again what I wrote, I explained what is happening and a solution was also provided (yt-dlp)
