### ISSUE TITLE
The desktop wallpaper was not restored when lively exited

### ISSUE THREAD

**Issue by iran1024** [rocksdanister/lively#918]
As the title says, the desktop wallpaper was not restored when lively exited

Often turns black solid wallpaper

I want to be able to restore the desktop wallpaper before starting lively when I exit lively, like Wallpaper Engine.

**Comment by rocksdanister** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**
Add any other context about the problem here.

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File

**Comment by iran1024** [comment]
Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior
A clear and concise description of what you expected to happen.

Screenshots/Video
If applicable, add screenshots/video to help explain your problem.

Desktop (please complete the following information):

OS: [e.g. Windows 10 1909]
Which wallpaper was running at the time if any.
Additional context
Add any other context about the problem here.

Log file (Important)
Share the diagnostic files by:
Open Lively settings (Gear icon) -> Misc. -> Log File
