### ISSUE TITLE
Graphic glitches on the app

### ISSUE THREAD

**Issue by IsaacMcbride** [rocksdanister/lively#927]
Hello! I first wanted to say the app is really good so far. However, a few things I've noticed is that the interface used to choose a live wallpaper or even to upload one has been very very unstable. Images appear super zoomed in, icons disappear from the screen along with button choices, and there is a huge glitch effect on every image and logo. While personally I didn't care about the app visual glitches as long as the wallpaper stayed up, it seemed to stop projecting it constantly. The live wallpaper I uploaded worked for maybe a few hours, but then when I get back onto my computer, the wallpaper is gone and lively refuses to open itself. I also could not manually open the app either. Then, on the button that shows the number of desktops to project the wallpaper on, it says there are 0 desktops and there is nothing I can do to change it. The only solution I have found so far is to just uninstall the app and reinstall, but Id rather not have to do that daily just to keep my live wallpaper up. I am on windows 11 btw

**Comment by rocksdanister** [comment]
I am guessing this is that issue caused by NahimicOSD dll injection:
https://www.reddit.com/r/LivelyWallpaper/comments/quv17n/i_noticed_somegraphical_issues_with_the_microsoft/

https://user-images.githubusercontent.com/17554161/144728899-1bc27747-4939-46d3-ad6d-3bca700915f8.mp4

Update your software drivers that use that.
