### ISSUE TITLE
hi i have a an issue that the wallpaper Fluids is a bit slow on the desktop and faster on the gif in the Lively

### ISSUE THREAD

**Issue by Fluffy227** [rocksdanister/lively#94]
i want a litle bit a help. The wallpaper Fluids is a bit slow on the desktop can you help me to fix it.

PC:This is sooooo nice program to work              PC 2: Sorry if it have some misspellings.

**Comment by rocksdanister** [comment]
Fluids requires a decent gpu to run at 60fps, what is your gpu?
You can try running the original in chrome: https://paveldogreat.github.io/WebGL-Fluid-Simulation/
If its slow in your browser, not much I can do.

Closing this as this looks like a wallpaper related issue rather than lively software itself.
