### ISSUE TITLE
Video web streams no longer work

### ISSUE THREAD

**Issue by laa413** [rocksdanister/lively#947]
I just updated to the newest desktop version of Lively v1.7.4.2.  Most of my wall papers come from web streams, and as of the new update they show the following error: "Your browser can't play this video.  Click to learn more."  I try to click but it is still a stream so I can't actually see the real issue.  I have posted a screenshot of an example.  Hopefully I am not the only one with the issue.  I am on Windows 10 version 21H2.  
<img width="1804" alt="Screenshot 2021-12-21 214311" src="https://user-images.githubusercontent.com/10834883/147026368-426f04ab-ea41-4574-b823-5eaca35b7b83.png">

**Comment by rocksdanister** [comment]
I removed the stream plugin because it is no longer being maintained by the developers. 
Right now I'm just loading the yt page.. some links may not work this way.

You can add the old stream plugin yourself (for installer version of Lively):
https://github.com/rocksdanister/lively/wiki/Streaming-Wallpaper#not-working

**Comment by laa413** [comment]
Thanks for the information :)
